/** Shared route-insertion recommendation card UI used across PMOS dialogs. */
function pmosRouteRecommendationCardStyles_() {
  return '.pmos-route-recommendations{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.pmos-route-rec{padding:11px;border:2px solid #d8e7ed;border-radius:10px;background:#fff;color:#293944;text-align:left;cursor:pointer}.pmos-route-rec:hover{background:#f3f9fb}.pmos-route-rec.selected{border-color:#017db1;background:#eaf6fb;box-shadow:0 0 0 2px rgba(1,125,177,.12)}.pmos-route-rec-title{display:flex;justify-content:space-between;gap:8px;font-size:12px;font-weight:900}.pmos-route-rec-title span{display:inline;color:#293944}.pmos-route-rec-reason{margin-top:7px;color:#52656e;font-size:10px;line-height:1.4}.pmos-route-rec-points{margin:8px 0 0;padding-left:16px;color:#52656e;font-size:10px;line-height:1.45}.pmos-route-rec-points li{margin:3px 0}.pmos-route-rec-points .muted{color:#7b898f}@media(max-width:760px){.pmos-route-recommendations{grid-template-columns:1fr}}';
}

function pmosRouteRecommendationCardScript_() {
  return String.raw`
function pmosRouteMinutes(value){var n=Math.max(0,Math.round(Number(value)||0)),h=Math.floor(n/60),m=n%60;return h?h+'h '+m+'m':m+' min'}
function pmosRoutePlacementText(p){p=p||{};var text='Week '+p.week+' - '+p.day+' - stop '+p.position;if(p.isFirstStop)text+=' (first stop)';else if(p.isLastStop)text+=' (last stop)';return text}
function pmosRouteRecommendationHtml(r,index,options){r=r||{};options=options||{};var primary=r.placements&&r.placements[0]||{},title=options.title||r.label||r.displayDate||'Route option',stop=Math.max(1,Math.round(Number(r.position||primary.position||1))),placement=String(stop)+(primary.isFirstStop?' (first stop)':primary.isLastStop?' (last stop)':''),points=[];if(options.dateLabel)points.push('<li><b>Date:</b> '+esc(options.dateLabel)+'</li>');if(options.includeRotation!==false){var rotation=r.rotationLabel||(r.rotationWeek?'Week '+r.rotationWeek:'');if(rotation)points.push('<li><b>'+((r.weeks||[]).length===2?'Rotation weeks':'Rotation week')+':</b> '+esc(rotation)+'</li>')}points.push('<li><b>Stop position:</b> '+esc(placement)+(r.customerCount!=null?' of '+esc(Number(r.customerCount||0)+1):'')+'</li>');if(r.previousName)points.push('<li><b>After:</b> '+esc(r.previousName)+'</li>');if(r.nextName)points.push('<li><b>Before:</b> '+esc(r.nextName)+'</li>');if(options.includeTemplate!==false&&r.placements&&r.placements.length)points.push('<li><b>Template:</b> '+esc(r.placements.map(pmosRoutePlacementText).join('; '))+'</li>');if(r.roadDataComplete){points.push('<li><b>Drive:</b> '+esc(pmosRouteMinutes(r.routeDriveMinutes))+' · '+Number(r.routeDistanceKm||0).toFixed(1)+' km</li>','<li><b>Stops:</b> '+Math.round(Number(r.customerCount||0)+1)+'</li>','<li><b>Estimated route*:</b> '+esc(pmosRouteMinutes(r.estimatedRouteMinutes))+'</li>','<li><b>Added:</b> +'+Number(r.addedDurationMinutes||0).toFixed(0)+' min · +'+Number(r.addedDistanceKm||0).toFixed(1)+' km</li>','<li class="muted">*'+Math.round(Number(r.serviceMinutes)||20)+'-minute average visits · '+esc(r.routeProvider||'RIE')+'</li>')}else points.push('<li>'+esc(r.reason||'GPS road-time check unavailable. Review this placement carefully.')+'</li>');return '<div class="pmos-route-rec-title"><span>'+(Number(index)+1)+'. '+esc(title)+'</span><span>'+esc(r.rating||'')+'</span></div>'+(r.reason?'<div class="pmos-route-rec-reason">'+esc(r.reason)+'</div>':'')+'<ul class="pmos-route-rec-points">'+points.join('')+'</ul>'}
function pmosSelectRouteCard(container,button){Array.prototype.forEach.call(container.querySelectorAll('.pmos-route-rec'),function(item){item.classList.remove('selected')});button.classList.add('selected')}
`;
}
