/**
 * Create Client dialog with RIE-assisted recurring-route placement.
 * The existing scoped Calendar transaction synchronizes the affected layers.
 */
function showAddMaintenanceClientV2() {
  const today = Utilities.formatDate(new Date(), PMOS.TIMEZONE, 'yyyy-MM-dd');
  const html = HtmlService.createHtmlOutput(`
<!DOCTYPE html><html><head><base target="_top"><style>
*{box-sizing:border-box}body{margin:0;padding:18px;font-family:Arial,sans-serif;color:#1f2937}h2{margin:0 0 5px}.muted{font-size:12px;color:#64748b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px 14px;margin-top:16px}.full{grid-column:1/-1}label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}input,select,textarea{width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:7px;font:inherit}textarea{min-height:68px}.section{grid-column:1/-1;margin-top:5px;padding-top:11px;border-top:1px solid #e2e8f0;font-size:13px;font-weight:700}.address-wrap{position:relative}.address-list{display:none;position:absolute;z-index:50;left:0;right:0;top:100%;max-height:235px;overflow:auto;background:white;border:1px solid #94a3b8;border-radius:0 0 8px 8px;box-shadow:0 10px 22px rgba(15,23,42,.18)}.address-option{display:block;width:100%;border:0;border-bottom:1px solid #e2e8f0;background:white;padding:10px;text-align:left;cursor:pointer}.address-option:hover,.address-option.active{background:#eff6ff}.address-main{font-weight:700}.address-details{display:none;grid-column:1/-1;padding:10px;background:#ecfdf5;border:1px solid #86efac;border-radius:8px;font-size:12px;line-height:1.5}.address-route-status{display:none;grid-column:1/-1;margin-top:-5px;padding:7px 10px;background:#eff6ff;border-radius:7px;color:#1d4ed8;font-size:12px}.note{grid-column:1/-1;padding:10px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;font-size:12px;white-space:pre-wrap}.recommendations{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.rec{padding:11px;text-align:left;background:#fff;border:2px solid #dbeafe;border-radius:10px;cursor:pointer}.rec.selected{border-color:#2563eb;background:#eff6ff}.rec-title{display:flex;justify-content:space-between;gap:8px;font-size:13px;font-weight:700}.rec-detail{margin-top:5px;color:#475569;font-size:11px;line-height:1.4}.manual{grid-column:1/-1;padding:10px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:9px}.manual-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.buttons{display:flex;gap:8px;margin-top:16px}.buttons button{padding:9px 13px;border:0;border-radius:8px;font-weight:700;cursor:pointer}.primary{background:#2563eb;color:white}.secondary{background:#e2e8f0}.status{margin-top:12px;min-height:48px;padding:10px;background:#f1f5f9;border-radius:8px;white-space:pre-wrap;font-size:12px}.error{background:#fee2e2;color:#991b1b}button:disabled{opacity:.5}@media(max-width:760px){.grid{grid-template-columns:1fr}.full,.section,.note,.recommendations,.manual{grid-column:1}.recommendations,.manual-grid{grid-template-columns:1fr}}
</style></head><body>
<div class="muted">Add the recurring client to PMOS and synchronize only the affected Calendar routes automatically.</div>
<div class="grid"><div class="section">Customer information</div>
<label class="full">Service address<div class="address-wrap"><input id="address" autocomplete="off" placeholder="Start typing and choose a complete address…" oninput="queueAddressSearch(this.value)" onfocus="queueAddressSearch(this.value)" onpaste="setTimeout(function(){queueAddressSearch(document.getElementById('address').value)},0)"><div id="addressList" class="address-list"></div></div></label><div id="addressDetails" class="address-details"></div><div id="addressRouteStatus" class="address-route-status"></div><label>First name<input id="firstName" autocomplete="given-name"></label><label>Last name<input id="lastName" autocomplete="family-name"></label><label>Phone<input id="phone" autocomplete="tel"></label><label>Email<input id="email" type="email" autocomplete="email"></label>
<div class="section">Maintenance schedule and route placement</div><label>Frequency<select id="frequency"><option>Weekly</option><option>Biweekly</option><option>Monthly</option><option>Twice Weekly</option></select></label><label>Effective date<input id="effectiveDate" type="date" value="${today}"></label>
<div id="recommendationStatus" class="note">Select a complete address above to calculate route placement.</div><div id="recommendations" class="recommendations"></div>
<div class="manual"><div class="muted" style="margin-bottom:8px"><b>Manual placement</b> — recommendations fill these fields, but every value remains editable.</div><div class="manual-grid"><label>Primary service day<select id="day"><option>Monday</option><option>Tuesday</option><option>Wednesday</option><option>Thursday</option><option>Friday</option></select></label><label id="secondDayLabel" style="display:none">Second service day<select id="secondDay"><option>Monday</option><option>Tuesday</option><option>Wednesday</option><option>Thursday</option><option>Friday</option></select></label><label id="weekLabel">Rotation week<select id="week"><option value="1">Week 1</option><option value="2">Week 2</option><option value="3">Week 3</option><option value="4">Week 4</option></select></label><label>Stop position<input id="stop" type="number" min="1" placeholder="Add at end of route"></label><label>Calendar title<input id="calendarTitle" placeholder="Defaults to last name"></label></div></div>
<div class="section">Additional client details</div><label class="full">Entry information<textarea id="entryInformation"></textarea></label><label class="full">Customer / service notes<textarea id="notes"></textarea></label>
<div class="section">Pool and equipment information</div><label>Sanitization type(s)<input id="sanitization"></label><label>Automation<input id="automation"></label><label>Pump<input id="pump"></label><label>Filter<input id="filter"></label><label>Heater<input id="heater"></label><label>Cleaner<input id="cleaner"></label><label>Cover<input id="cover"></label><label>Service season<select id="yearRound"><option value="No">Seasonal</option><option value="Yes">Year Round</option></select></label></div>
<div class="buttons"><button id="refreshButton" class="secondary">Refresh Recommendations</button><button id="saveButton" class="primary">Create Client</button><button id="retryButton" class="secondary" style="display:none">Retry Calendar Sync</button><button id="cancelButton" class="secondary">Cancel</button></div><div id="status" class="status">Ready.</div>
<script>
var recTimer=null,addressTimer=null,recRequest=0,addressRequest=0,currentRecommendations=[],selectedPlacements=[],savedCustomer=null,selectedAddress=null,addressSuggestionCache={},lastAddressItems=[];
function byId(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
function setAddressRouteStatus(message,isError){var box=byId('addressRouteStatus');box.textContent=message||'';box.style.display=message?'block':'none';box.style.background=isError?'#fee2e2':'#eff6ff';box.style.color=isError?'#991b1b':'#1d4ed8'}
function formValues(){var firstName=byId('firstName').value,lastName=byId('lastName').value;return{firstName:firstName,lastName:lastName,name:lastName,address:byId('address').value,addressVerified:!!selectedAddress,addressDetails:selectedAddress,phone:byId('phone').value,email:byId('email').value,entryInformation:byId('entryInformation').value,notes:byId('notes').value,sanitization:byId('sanitization').value,automation:byId('automation').value,pump:byId('pump').value,filter:byId('filter').value,heater:byId('heater').value,cleaner:byId('cleaner').value,cover:byId('cover').value,yearRound:byId('yearRound').value,frequency:byId('frequency').value,effectiveDate:byId('effectiveDate').value,week:Number(byId('week').value),day:byId('day').value,secondDay:byId('secondDay').value,stop:byId('stop').value,calendarTitle:byId('calendarTitle').value,recommendedPlacements:selectedPlacements}}
function scheduleChanged(){selectedPlacements=[];var f=byId('frequency').value;byId('secondDayLabel').style.display=f==='Twice Weekly'?'flex':'none';byId('weekLabel').style.display=(f==='Weekly'||f==='Twice Weekly')?'none':'flex';queueRecommendations(false)}
function queueRecommendations(immediate){clearTimeout(recTimer);if(selectedAddress)setAddressRouteStatus('Searching for the best route insertions…',false);recTimer=setTimeout(loadRecommendations,immediate?50:700)}
function loadRecommendations(){var data=formValues();selectedPlacements=[];if(!selectedAddress){currentRecommendations=[];byId('recommendations').innerHTML='';byId('recommendationStatus').textContent='Choose a complete address suggestion before calculating route placement.';setAddressRouteStatus('',false);return}var request=++recRequest;setAddressRouteStatus('Searching for the best route insertions…',false);byId('recommendationStatus').textContent='Calculating GPS placement in the existing PMOS route layers…';google.script.run.withSuccessHandler(function(result){if(request!==recRequest)return;currentRecommendations=(result&&result.recommendations)||[];setAddressRouteStatus(currentRecommendations.length?'Best route insertions are ready below.':'Route search finished; no automatic placement was available.',!currentRecommendations.length);byId('recommendationStatus').textContent=(result&&result.qualityMessage)||'Recommendations calculated.';renderRecommendations()}).withFailureHandler(function(error){if(request!==recRequest)return;currentRecommendations=[];byId('recommendations').innerHTML='';setAddressRouteStatus('Route insertion search could not be completed. You can continue filling the form and retry below.',true);byId('recommendationStatus').textContent='Route recommendations could not be calculated.\\n'+(error&&error.message?error.message:String(error))}).recommendMaintenanceClientRotations(data)}
function fmtMinutes(v){var n=Math.max(0,Math.round(Number(v)||0)),h=Math.floor(n/60),m=n%60;return h?h+'h '+m+'m':m+' min'}
function renderRecommendations(){var box=byId('recommendations');box.innerHTML='';currentRecommendations.forEach(function(r,i){var b=document.createElement('button');b.type='button';b.className='rec';b.addEventListener('click',function(){document.querySelectorAll('.rec').forEach(function(x){x.classList.remove('selected')});b.classList.add('selected');selectedPlacements=(r.placements||[]).map(function(p){return{week:p.week,day:p.day,layer:p.layer,position:p.position}});byId('day').value=r.day;if(r.secondDay)byId('secondDay').value=r.secondDay;if(r.week)byId('week').value=String(r.week);byId('stop').value='';setAddressRouteStatus('Route placement selected. Continue completing the form.',false);byId('recommendationStatus').textContent='Recommendation applied to '+selectedPlacements.length+' exact Route Template layer(s). Enter a stop only to override every recommended position.'});var between=r.previousName||r.nextName?(r.previousName||'Start of route')+' → New customer → '+(r.nextName||'End of route'):'New customer at route start';var layers=(r.placements||[]).map(function(p){return p.layer+' (stop '+p.position+')'}).join('; ');var metrics=r.roadDataComplete?'<div class="rec-detail"><b>Drive Time</b> '+esc(fmtMinutes(r.routeDriveMinutes))+' · <b>Drive Distance</b> '+Number(r.routeDistanceKm||0).toFixed(1)+' km</div><div class="rec-detail"><b>Route Stops</b> '+Math.round(Number(r.customerCount||0)+1)+' · <b>Estimated Route Length*</b> '+esc(fmtMinutes(r.estimatedRouteMinutes))+'</div><div class="rec-detail">Added driving: +'+Number(r.addedDurationMinutes||0).toFixed(0)+' min · +'+Number(r.addedDistanceKm||0).toFixed(1)+' km · '+esc(r.routeProvider||'RIE')+'</div><div class="rec-detail">*Based on '+Math.round(Number(r.serviceMinutes)||20)+'-minute average visits.</div>':'<div class="rec-detail">GPS road-time check unavailable. Review manual placement.</div>';b.innerHTML='<div class="rec-title"><span>'+(i+1)+'. '+esc(r.label)+'</span><span>'+esc(r.rating)+'</span></div><div class="rec-detail">'+esc(r.rotationLabel)+'</div><div class="rec-detail">'+esc(between)+'</div><div class="rec-detail">'+esc(layers)+'</div>'+metrics;box.appendChild(b)})}
function clearAddressSelection(){selectedAddress=null;selectedPlacements=[];byId('addressDetails').style.display='none';byId('addressDetails').textContent='';byId('recommendations').innerHTML='';currentRecommendations=[];setAddressRouteStatus('',false)}
function queueAddressSearch(value){clearTimeout(addressTimer);clearTimeout(recTimer);var q=String(value==null?byId('address').value:value).trim(),key=q.toLowerCase(),request=++addressRequest;if(selectedAddress&&q!==selectedAddress.address)clearAddressSelection();if(q.length<3){byId('recommendationStatus').textContent='Type at least 3 address characters to see suggestions.';hideAddresses();return}var immediate=addressSuggestionCache[key]||lastAddressItems.filter(function(item){return String(item.address||'').toLowerCase().indexOf(key)>=0});if(immediate.length){renderAddresses(immediate);byId('recommendationStatus').textContent='Choose a complete address suggestion.'}else{byId('recommendationStatus').textContent='Searching for complete Canadian addresses…'}if(addressSuggestionCache[key])return;addressTimer=setTimeout(function(){google.script.run.withSuccessHandler(function(items){if(request!==addressRequest)return;items=items||[];addressSuggestionCache[key]=items;lastAddressItems=items;renderAddresses(items);byId('recommendationStatus').textContent=items.length?'Choose a complete address suggestion.':'No complete address matches yet. Continue typing.'}).withFailureHandler(function(error){if(request!==addressRequest)return;if(!immediate.length)hideAddresses();byId('recommendationStatus').textContent='Address suggestions could not load.\\n'+(error&&error.message?error.message:String(error))}).suggestPmosAddresses(q,8)},180)}
function applyResolvedAddress(item){addressRequest++;clearTimeout(addressTimer);clearTimeout(recTimer);selectedAddress=item;byId('address').value=item.address;var box=byId('addressDetails');box.innerHTML='<b>Confirmed address</b><br>'+esc(item.street)+'<br>'+esc(item.city)+', '+esc(item.province)+' '+esc(item.postalCode)+'<br>'+esc(item.country);box.style.display='block';hideAddresses();setAddressRouteStatus('Address confirmed. Searching for the best route insertions…',false);byId('recommendationStatus').textContent='Complete address confirmed. Calculating GPS route recommendations…';setTimeout(loadRecommendations,0)}
function renderAddresses(items){var list=byId('addressList');list.innerHTML='';if(!items.length){hideAddresses();return}items.forEach(function(item){var b=document.createElement('button');b.type='button';b.className='address-option';b.innerHTML='<div class="address-main">'+esc(item.address)+'</div>';b.addEventListener('mousedown',function(event){event.preventDefault();hideAddresses();setAddressRouteStatus('Confirming the selected address…',false);byId('recommendationStatus').textContent='Confirming the selected address…';google.script.run.withSuccessHandler(applyResolvedAddress).withFailureHandler(function(error){clearAddressSelection();setAddressRouteStatus(error&&error.message?error.message:String(error),true);byId('recommendationStatus').textContent=error&&error.message?error.message:String(error)}).confirmPmosSelectedAddress(item)});list.appendChild(b)});list.style.display='block'}
function hideAddresses(){byId('addressList').style.display='none';byId('addressList').innerHTML=''}
function saveCustomer(){var data=formValues();if(!data.firstName.trim()||!data.lastName.trim()||!data.address.trim()){byId('status').className='status error';byId('status').textContent='First name, last name, and service address are required.';return}if(!selectedAddress){byId('status').className='status error';byId('status').textContent='Choose and confirm a complete address suggestion before creating the client.';return}if(data.frequency==='Twice Weekly'&&data.day===data.secondDay){byId('status').className='status error';byId('status').textContent='Twice-weekly service requires two different weekdays.';return}byId('saveButton').disabled=true;byId('status').className='status';byId('status').textContent='Creating the client, auditing affected routes, and synchronizing Calendar automatically…';google.script.run.withSuccessHandler(function(result){savedCustomer=Object.assign({},data,{customerId:result.customerId,affectedLayers:(result.routeRows||[]).map(function(row){return row.layer})});byId('status').textContent=result.summary;byId('saveButton').textContent='Created';if(result.calendarStatus==='SYNC_ERROR'){byId('status').className='status error';byId('retryButton').style.display='inline-block'}else{setTimeout(function(){google.script.host.close()},1200)}}).withFailureHandler(function(error){byId('saveButton').disabled=false;byId('status').className='status error';byId('status').textContent=error&&error.message?error.message:String(error)}).createMaintenanceCustomerAndAutoSync(data)}
function retryCalendar(){if(!savedCustomer)return;byId('retryButton').disabled=true;byId('status').className='status';byId('status').textContent='Retrying automatic Calendar Sync…';google.script.run.withSuccessHandler(function(result){byId('status').textContent='Calendar synchronized successfully.\\nCreated: '+Number(result.created||0)+'\\nUpdated: '+Number(result.updated||result.adjusted||0);byId('retryButton').style.display='none';setTimeout(function(){google.script.host.close()},1200)}).withFailureHandler(function(error){byId('retryButton').disabled=false;byId('status').className='status error';byId('status').textContent='Calendar Sync is still paused safely:\\n'+(error&&error.message?error.message:String(error))}).retryAddedMaintenanceCustomerCalendar(savedCustomer)}
function clearSelectedPlacement(){selectedPlacements=[];document.querySelectorAll('.rec').forEach(function(x){x.classList.remove('selected')})}
function initializeDialog(){var address=byId('address');address.addEventListener('blur',function(){setTimeout(hideAddresses,180)});byId('frequency').addEventListener('change',scheduleChanged);['day','secondDay','week'].forEach(function(id){byId(id).addEventListener('change',clearSelectedPlacement)});byId('refreshButton').addEventListener('click',loadRecommendations);byId('saveButton').addEventListener('click',saveCustomer);byId('retryButton').addEventListener('click',retryCalendar);byId('cancelButton').addEventListener('click',function(){google.script.host.close()});google.script.run.preparePmosAddressSuggestions();scheduleChanged()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initializeDialog)}else{initializeDialog()}
</script></body></html>`).setWidth(900).setHeight(840);
  SpreadsheetApp.getUi().showModalDialog(html, 'Add Maintenance Client');
}
