/**
 * Shared equipment/catalog enhancements used by every PMOS customer form.
 *
 * Extends the common editor rather than creating Sheets/Web variants. Adds
 * broader legacy pump/chlorinator coverage and explicit chemistry-automation
 * accessories.
 */
function pmosCustomerEquipmentCatalogStyles_() {
  return (
        '.chemistry-selectors{display:grid;grid-column:1/-1;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}' +
        '.chemistry-selectors>label,.chemistry-component-row>label,.chemistry-other-equipment{display:flex;flex-direction:column;gap:5px;color:#6f7d84;font-size:11px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}' +
        '.chemistry-equipment-host{grid-column:1/-1;width:100%;box-sizing:border-box}.chemistry-equipment-card{width:100%;margin-top:2px;box-sizing:border-box}' +
        '.chemistry-component-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.chemistry-component-row{display:grid;grid-template-columns:minmax(110px,.65fr) minmax(170px,1.35fr) minmax(125px,.8fr);gap:8px;align-items:end;padding:8px;border:1px solid #dbeafe;border-radius:8px;background:#f8fafc}.chemistry-component-row>label:last-child:nth-child(2){grid-column:2/-1}.chemistry-other-equipment{grid-column:1/-1}' +
        '.chemistry-component-name{align-self:center;color:#293944;font-size:12px;font-weight:900}.chemistry-other-equipment{padding-top:3px}' +
        '@media(max-width:1100px){.chemistry-component-list{grid-template-columns:1fr}}@media(max-width:760px){.chemistry-selectors,.chemistry-component-row{grid-template-columns:1fr}.chemistry-component-row>label:last-child:nth-child(2){grid-column:auto}}'
  );
}

function pmosCustomerEquipmentCatalogScript_() {
  return String.raw`
(function(){
  function pmosNormEquipmentNumber(value){return String(value||'').trim().toUpperCase().replace(/[\s_]/g,'-')}
  function pmosCatalogNumberValue(item){return typeof item==='string'?item:(item&&item.value)||''}
  function pmosAppendEquipmentModel(unit,make,name,numbers){
    PMOS_EQUIPMENT_CATALOG[unit]=PMOS_EQUIPMENT_CATALOG[unit]||{};PMOS_EQUIPMENT_CATALOG[unit][make]=PMOS_EQUIPMENT_CATALOG[unit][make]||[];
    var list=PMOS_EQUIPMENT_CATALOG[unit][make],existing=list.filter(function(item){return String(item.name||'').toLowerCase()===String(name||'').toLowerCase()})[0];
    if(!existing){existing={name:name,numbers:[]};list.push(existing)}
    var seen={};(existing.numbers||[]).forEach(function(value){seen[pmosNormEquipmentNumber(pmosCatalogNumberValue(value))]=true});
    (numbers||[]).forEach(function(value){var key=pmosNormEquipmentNumber(pmosCatalogNumberValue(value));if(key&&!seen[key]){existing.numbers.push(value);seen[key]=true}})
  }
  function pmosAppendSanitizerModel(type,make,name,numbers){
    PMOS_SANITIZER_CATALOG[type]=PMOS_SANITIZER_CATALOG[type]||{};PMOS_SANITIZER_CATALOG[type][make]=PMOS_SANITIZER_CATALOG[type][make]||[];
    var list=PMOS_SANITIZER_CATALOG[type][make],existing=list.filter(function(item){return String(item.name||'').toLowerCase()===String(name||'').toLowerCase()})[0];
    if(!existing){existing={name:name,numbers:[]};list.push(existing)}
    var seen={};(existing.numbers||[]).forEach(function(value){seen[pmosNormEquipmentNumber(pmosCatalogNumberValue(value))]=true});
    (numbers||[]).forEach(function(value){var key=pmosNormEquipmentNumber(pmosCatalogNumberValue(value));if(key&&!seen[key]){existing.numbers.push(value);seen[key]=true}})
  }

  /* Hayward MaxFlo XL single-speed family. */
  pmosAppendEquipmentModel('pump','Hayward','MaxFlo XL Single-Speed 0.75 HP',['SP2305X7','SP2305X7EE','SP2305X7EESP']);
  pmosAppendEquipmentModel('pump','Hayward','MaxFlo XL Single-Speed 1.0 HP',['SP2307X10']);
  pmosAppendEquipmentModel('pump','Hayward','MaxFlo XL Single-Speed 1.5 HP',['SP2310X15']);
  pmosAppendEquipmentModel('pump','Hayward','MaxFlo XL Single-Speed 2.0 HP',['SP2315X20']);

  /* Jandy legacy/current single-speed families retained for field identification. */
  pmosAppendEquipmentModel('pump','Jandy','FloPro Single-Speed',['FHPM.75','FHPM1.0','FHPM1.5','FHPM2.0','FHPM2.5']);
  pmosAppendEquipmentModel('pump','Jandy','Stealth SHPF Single-Speed',['SHPF.50','SHPF.75','SHPF1.0','SHPF1.5','SHPF2.0','SHPF3.0','SHPF5.0','SHPF5.0TEFC','SHPF1.0-3PH','SHPF1.5-3PH','SHPF2.0-3PH','SHPF3.0-3PH','SHPF5.0-3PH']);
  pmosAppendEquipmentModel('pump','Jandy','Stealth SHPM Single-Speed',['SHPM.75','SHPM1.0','SHPM1.5','SHPM2.0','SHPM2.5']);

  /* Sta-Rite Max-E-Pro single-speed/legacy identifiers. */
  pmosAppendEquipmentModel('pump','Sta-Rite','Max-E-Pro Single-Speed',['348185','P6E6C-204L-INT','P6E6D-205L-INT','348150-INT','348151-INT','348152-INT','348153-INT']);

  /* Hayward residential and commercial tablet/puck feeders, including legacy commercial sizes. */
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','CL100 Inline',['CL100','CL100EF']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','CL110 Offline',['CL110']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','CL200 Inline',['CL200','CL200EF','CL2002S']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','CL220 Offline',['CL220','CL220EF']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','Commercial Chemical Feeder 16 lb',['C250EXP','C0250EXPE','C250CF']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','Commercial Chemical Feeder 30 lb',['C500EXP','C0500EXPE','C500CF']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','Commercial Chemical Feeder 50 lb (Legacy)',['C1100CF']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','Commercial Chemical Feeder 70 lb (Legacy)',['C1800CF']);
  pmosAppendSanitizerModel('CHLORINE_FEEDER','Hayward','Commercial Chemical Feeder 90 lb (Legacy)',['C2400CF']);

  function pmosFindSanitizerByTypeNumber(type,value){
    var target=pmosNormEquipmentNumber(value),found=null;if(!target)return null;
    Object.keys(PMOS_SANITIZER_CATALOG[type]||{}).some(function(make){return (PMOS_SANITIZER_CATALOG[type][make]||[]).some(function(model){var modelExact=(model.modelNumbers||[]).filter(function(number){return pmosNormEquipmentNumber(pmosCatalogNumberValue(number))===target})[0],partExact=(model.partNumbers||model.numbers||[]).filter(function(number){return pmosNormEquipmentNumber(pmosCatalogNumberValue(number))===target})[0],exact=modelExact||partExact;if(exact){found={make:make,model:model.name,field:modelExact?'modelNumber':'partNumber',number:pmosCatalogNumberValue(exact)};return true}return false})});return found
  }
  /* Correct reverse lookup inside the sanitizer type selected on the card. */
  document.addEventListener('input',function(event){var input=event.target,field=input&&input.getAttribute('data-equipment-field');if(field!=='modelNumber'&&field!=='partNumber')return;var card=input.closest('.equipment-card'),type=card&&card.getAttribute('data-equipment-type');if(!type||!PMOS_SANITIZER_CATALOG[type])return;var match=pmosFindSanitizerByTypeNumber(type,input.value);if(!match)return;var make=card.querySelector('[data-equipment-field="make"]'),model=card.querySelector('[data-equipment-field="model"]');if(make){make.value=match.make;make.dispatchEvent(new Event('input',{bubbles:true}))}if(model){model.value=match.model;model.dispatchEvent(new Event('input',{bubbles:true}))}var number=card.querySelector('[data-equipment-field="'+match.field+'"]');if(number)number.value=match.number});

  var previousEquipmentTypeLabel=equipmentTypeLabel;
  equipmentTypeLabel=function(type){return {FLOW_CELL:'Flow Cell',ACID_TANK:'Acid Tank',CHLORINE_TANK:'Chlorine Tank',PH_PROBE:'pH Probe',ORP_PROBE:'ORP Probe'}[type]||previousEquipmentTypeLabel(type)};
})();
`;
}

/** Shared body overview and standalone-spa behavior used by every customer form. */
(function () {
  if (typeof pmosCustomerEquipmentEditorStyles_ === 'function') {
    const baseStyles = pmosCustomerEquipmentEditorStyles_;
    pmosCustomerEquipmentEditorStyles_ = function () {
      return baseStyles() + pmosCustomerEquipmentCatalogStyles_() +
        '.body-grid{grid-template-columns:repeat(5,minmax(0,1fr))}' +
        '.body-overview-field select,.body-overview-field input{min-width:0}' +
        '.pmos-volume-field{grid-column:span 2}.pmos-volume-control{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:7px}.pmos-volume-unit{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;overflow:hidden;border:1px solid #bfcbd1;border-radius:7px;background:#fff}.pmos-volume-unit:focus-within{border-color:#017db1;box-shadow:0 0 0 3px rgba(1,125,177,.13)}.pmos-volume-unit input{width:100%;border:0!important;box-shadow:none!important;background:transparent!important}.pmos-volume-suffix{padding-right:9px;color:#64737b;font-size:11px;font-weight:900;white-space:nowrap}.pmos-volume-divider{color:#64737b;font-weight:900}' +
        '.body-title,.unit-title{font-size:14px}.equipment-head{font-size:13px}' +
        '.body-grid>label,.equipment-grid>label,.chemistry-fields>label,.automation-fields>label,.spa-details>label,.spa-unit-fields>label,.chemistry-selectors>label,.chemistry-component-row>label,.chemistry-other-equipment,.pmos-equipment-notes label,.pmos-solar-equipment-grid label{font-size:12px}' +
        '.body-grid input,.body-grid select,.equipment-grid input,.equipment-grid select,.chemistry-fields input,.automation-fields input,.automation-fields select,.spa-details input,.spa-details select,.spa-unit-fields input,.pmos-solar-equipment-grid input,.pmos-solar-equipment-grid textarea{font-size:13px}' +
        '.inline-button,.remove-button,.pmos-solar-add{font-size:12px}.pmos-shared-equipment-summary{display:none;grid-column:1/-1;padding:10px 12px;border:1px solid #bae6fd;border-radius:8px;background:#f0f9ff;color:#34515f;font-size:12px;line-height:1.45}.pmos-shared-equipment-summary.open{display:block}.pmos-shared-equipment-summary strong{color:#0f5470}' +
        '@media(max-width:960px){.body-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}' +
        '@media(max-width:760px){.body-grid{grid-template-columns:1fr}.pmos-volume-field{grid-column:auto}}';
    };
  }

  if (typeof pmosCustomerEquipmentEditorScript_ !== 'function') return;
  const baseScript = pmosCustomerEquipmentEditorScript_;
  pmosCustomerEquipmentEditorScript_ = function () {
    return baseScript() + pmosCustomerEquipmentCatalogScript_() + String.raw`
(function(){
  var PMOS_BODY_SHAPES=['Rectangle','Round','Oval','Kidney','L-Shaped','Roman','Grecian','Lazy L','Figure Eight','Coffin','Free Form','Other'];
  var PMOS_MAKE_ORDER=['Pentair','Hayward','Jandy','Sta-Rite','Nature2'];
  var PMOS_LITRES_PER_US_GALLON=3.785411784;
  function pmosReorderCatalogMakes(){Object.keys(PMOS_SANITIZER_CATALOG||{}).forEach(function(type){var source=PMOS_SANITIZER_CATALOG[type]||{},ordered={};PMOS_MAKE_ORDER.forEach(function(make){if(source[make])ordered[make]=source[make]});Object.keys(source).forEach(function(make){if(!ordered[make])ordered[make]=source[make]});PMOS_SANITIZER_CATALOG[type]=ordered})}
  function pmosVolumeDigits(value){return String(value==null?'':value).replace(/[^0-9]/g,'').replace(/^0+(?=\d)/,'')}
  function pmosFormatVolumeNumber(value){var digits=pmosVolumeDigits(value);return digits&&Number(digits)>0?digits.replace(/\B(?=(\d{3})+(?!\d))/g,','):''}
  function pmosParseVolume(value){var raw=String(value||'').trim(),gallonMatch=raw.match(/([\d,.]+)\s*(?:us\s*)?(?:gal|gallon)/i),litreMatch=raw.match(/([\d,.]+)\s*(?:l|litre|liter)(?:s)?\b/i),plain=raw.match(/[\d,.]+/),gallons=gallonMatch?Number(gallonMatch[1].replace(/,/g,'')):0,litres=litreMatch?Number(litreMatch[1].replace(/,/g,'')):0;if(!gallons&&!litres&&plain){var number=Number(plain[0].replace(/,/g,''));if(/gal/i.test(raw))gallons=number;else litres=number}if(!litres&&gallons)litres=Math.round(gallons*PMOS_LITRES_PER_US_GALLON);if(!gallons&&litres)gallons=Math.round(litres/PMOS_LITRES_PER_US_GALLON);return{litres:litres?Math.round(litres):0,gallons:gallons?Math.round(gallons):0}}
  function pmosCombinedVolume(litres,gallons){return litres&&gallons?pmosFormatVolumeNumber(litres)+' L / '+pmosFormatVolumeNumber(gallons)+' gal':''}
  function pmosRestoreVolumeCaret(input,digitsBefore){if(!input||typeof input.setSelectionRange!=='function')return;var position=0,count=0;while(position<input.value.length&&count<digitsBefore){if(/\d/.test(input.value.charAt(position)))count++;position++}input.setSelectionRange(position,position)}
  function pmosFormatVolumeInput(input){var caret=input.selectionStart==null?String(input.value||'').length:input.selectionStart,digitsBefore=pmosVolumeDigits(String(input.value||'').slice(0,caret)).length;input.value=pmosFormatVolumeNumber(input.value);pmosRestoreVolumeCaret(input,digitsBefore);return Number(pmosVolumeDigits(input.value)||0)}
  function pmosSyncVolumeFromUnit(input){var control=input&&input.closest('.pmos-volume-control'),canonical=control&&control.parentNode&&control.parentNode.querySelector('[data-body-field="volume"]');if(!control||!canonical)return;var litresInput=control.querySelector('[data-pmos-volume-unit="litres"]'),gallonsInput=control.querySelector('[data-pmos-volume-unit="gallons"]'),source=pmosFormatVolumeInput(input),litres=0,gallons=0;if(source){if(input===litresInput){litres=source;gallons=Math.round(litres/PMOS_LITRES_PER_US_GALLON);gallonsInput.value=pmosFormatVolumeNumber(gallons)}else{gallons=source;litres=Math.round(gallons*PMOS_LITRES_PER_US_GALLON);litresInput.value=pmosFormatVolumeNumber(litres)}}else{litresInput.value='';gallonsInput.value=''}canonical.value=pmosCombinedVolume(litres,gallons)}
  function pmosHydrateVolumeControl(canonical,value){if(!canonical)return;var label=canonical.closest('label'),control=label&&label.querySelector('.pmos-volume-control');canonical.value=String(value==null?canonical.value||'':value);if(!control)return;var parsed=pmosParseVolume(canonical.value),litres=control.querySelector('[data-pmos-volume-unit="litres"]'),gallons=control.querySelector('[data-pmos-volume-unit="gallons"]');litres.value=pmosFormatVolumeNumber(parsed.litres);gallons.value=pmosFormatVolumeNumber(parsed.gallons);canonical.value=pmosCombinedVolume(parsed.litres,parsed.gallons)}
  function pmosEnsureVolumeControl(canonical){if(!canonical)return;if(canonical.__pmosVolumeWired){pmosHydrateVolumeControl(canonical);return}var label=canonical.closest('label');if(!label)return;canonical.__pmosVolumeWired=true;canonical.type='hidden';canonical.setAttribute('aria-hidden','true');label.classList.add('pmos-volume-field');var control=document.createElement('div');control.className='pmos-volume-control';control.innerHTML='<span class="pmos-volume-unit"><input type="text" inputmode="numeric" autocomplete="off" data-pmos-volume-unit="litres" aria-label="Volume in litres" placeholder="70,000"><span class="pmos-volume-suffix">L</span></span><span class="pmos-volume-divider" aria-hidden="true">/</span><span class="pmos-volume-unit"><input type="text" inputmode="numeric" autocomplete="off" data-pmos-volume-unit="gallons" aria-label="Volume in US gallons" placeholder="18,492"><span class="pmos-volume-suffix">gal</span></span>';canonical.insertAdjacentElement('afterend',control);Array.prototype.forEach.call(control.querySelectorAll('[data-pmos-volume-unit]'),function(input){input.addEventListener('input',function(){pmosSyncVolumeFromUnit(this)})});pmosHydrateVolumeControl(canonical)}
  function pmosSetVolumeValue(target,value){var canonical=target&&target.matches&&target.matches('[data-body-field="volume"]')?target:target&&target.querySelector&&target.querySelector('[data-body-field="volume"]');if(!canonical)return;canonical.value=String(value==null?'':value);pmosEnsureVolumeControl(canonical);pmosHydrateVolumeControl(canonical)}
  window.pmosVolumeControl={parse:pmosParseVolume,formatNumber:pmosFormatVolumeNumber,setValue:pmosSetVolumeValue};
  function pmosInstallBodyOverview(card){if(!card)return;var existing=card.querySelector('[data-body-field="volume"]');if(existing){pmosEnsureVolumeControl(existing);return}var sanitization=card.querySelector('[data-body-field="sanitization"]'),anchor=sanitization&&sanitization.closest('label');if(!anchor)return;anchor.classList.add('body-overview-field');var shape=document.createElement('label'),volume=document.createElement('label');shape.className='body-overview-field';volume.className='body-overview-field pmos-volume-field';shape.innerHTML='Shape<select data-body-field="shape"><option value="">Select shape</option>'+PMOS_BODY_SHAPES.map(function(value){return'<option value="'+esc(value)+'">'+esc(value)+'</option>'}).join('')+'</select>';volume.innerHTML='Volume<input type="hidden" data-body-field="volume">';anchor.insertAdjacentElement('afterend',shape);shape.insertAdjacentElement('afterend',volume);pmosInstallBodyOverview(card)}
  function pmosShortenCartridgeLabels(root){Array.prototype.forEach.call((root||document).querySelectorAll('[data-cartridge-set-wrap]'),function(wrap){var label=wrap.matches&&wrap.matches('label')?wrap:wrap.querySelector('label');if(!label)return;Array.prototype.forEach.call(label.childNodes,function(node){if(node.nodeType===3&&/replacement\s+cartridge\s+set/i.test(node.nodeValue||''))node.nodeValue=(node.nodeValue||'').replace(/Replacement\s+Cartridge\s+Set/i,'Cartridge Set')})})}
  function pmosInstallFilterModelNumber(root){Array.prototype.forEach.call((root||document).querySelectorAll('[data-body-field="filterModel"],[data-equipment-field="filterModel"]'),function(model){var featureCard=model.closest('.equipment-card[data-equipment-type="WATER_FEATURE"]');if(featureCard&&!model.closest('[data-water-feature-equipment]'))return;var attribute=model.hasAttribute('data-body-field')?'data-body-field':'data-equipment-field',container=model.closest('.water-body,[data-water-feature-equipment],.equipment-card'),field=container&&container.querySelector('['+attribute+'="filterModelNumber"]'),label,suffix;if(!field){label=document.createElement('label');label.setAttribute('data-filter-model-number','true');label.innerHTML='Model Number<input '+attribute+'="filterModelNumber" placeholder="select or type">';var anchor=model.closest('label');if(anchor)anchor.insertAdjacentElement('afterend',label);field=label.querySelector('input')}label=field&&field.closest('label');if(field&&!smartListId(field)){suffix='filterModelNumbers_'+String(Date.now())+'_'+Math.round(Math.random()*100000);field.setAttribute('list',suffix);var datalist=document.createElement('datalist');datalist.id=suffix;if(label)label.appendChild(datalist);else container.appendChild(datalist);if(typeof enhanceEditableSelects==='function')enhanceEditableSelects(label||container)}if(field&&!field.__pmosFilterNumberWired){field.__pmosFilterNumberWired=true;field.addEventListener('input',function(){pmosSyncFilterModelNumber(this,true)})}pmosSyncFilterModelNumber(model,false)})}
  function pmosCorrectFilterCatalog(){var sand=PMOS_FILTER_MODEL_CATALOG&&PMOS_FILTER_MODEL_CATALOG.Pentair&&PMOS_FILTER_MODEL_CATALOG.Pentair.Sand;if(!sand)return;PMOS_FILTER_MODEL_CATALOG.Pentair.Sand=sand.map(function(value){return String(value).replace(/^SD35 \([^)]*\)/,'SD35 (16.5 in · 100 lb)').replace(/^SD40 \([^)]*\)/,'SD40 (19.5 in · 150 lb)').replace(/^SD60 \([^)]*\)/,'SD60 (22.5 in · 250 lb)')})}
  function pmosFilterPartNumber(make,model){return String(make||'').toLowerCase()==='pentair'&&/^SD60(?:\s|\(|$)/i.test(String(model||''))?'145322':''}
  function pmosFilterContext(input){var body=input.closest('.water-body'),feature=input.closest('[data-water-feature-equipment]'),card=input.closest('.equipment-card');if(feature)return{root:feature,make:'[data-equipment-field="filterMake"]',model:'[data-equipment-field="filterModel"]',attribute:'data-equipment-field'};if(card&&card.getAttribute('data-equipment-type')==='FILTER')return{root:card,make:'[data-equipment-field="make"]',model:'[data-equipment-field="filterModel"]',attribute:'data-equipment-field'};if(body)return{root:body,make:'[data-body-field="filterMake"]',model:'[data-body-field="filterModel"]',attribute:'data-body-field'};return null}
  function pmosFilterModels(context){var make=fieldValue(context.root,context.make),type=fieldValue(context.root,'['+context.attribute+'="filterType"]'),makeKey=Object.keys(PMOS_FILTER_MODEL_CATALOG||{}).filter(function(value){return value.toLowerCase()===String(make||'').toLowerCase()})[0],groups=makeKey?PMOS_FILTER_MODEL_CATALOG[makeKey]||{}:{},typeKey=Object.keys(groups).filter(function(value){return value.toLowerCase()===String(type||'').toLowerCase()})[0];return typeKey?groups[typeKey]||[]:[]}
  function pmosFilterModelCode(value){return String(value||'').replace(/\s*\([^)]*\)\s*$/,'').trim()}
  function pmosSyncFilterModelNumber(input,fromNumber){var context=pmosFilterContext(input);if(!context)return;var model=context.root.querySelector(context.model),number=context.root.querySelector('['+context.attribute+'="filterModelNumber"]');if(!model||!number)return;var models=pmosFilterModels(context),list=document.getElementById(smartListId(number));if(list)list.innerHTML=models.map(function(value){return'<option value="'+esc(pmosFilterModelCode(value))+'">'}).join('');if(fromNumber){var match=models.filter(function(value){return pmosFilterModelCode(value).toLowerCase()===String(number.value||'').trim().toLowerCase()})[0];if(match&&model.value!==match){model.value=match;model.dispatchEvent(new Event('input',{bubbles:true}))}}else{var selected=models.filter(function(value){return value.toLowerCase()===String(model.value||'').trim().toLowerCase()})[0];number.value=selected?pmosFilterModelCode(selected):''}}
  function pmosSyncFilterPartNumber(input,saved){var context=pmosFilterContext(input);if(!context)return;var make=fieldValue(context.root,context.make),model=fieldValue(context.root,context.model),part=saved||pmosFilterPartNumber(make,model),field=context.root.querySelector('['+context.attribute+'="filterPartNumber"]'),wrap=field&&field.closest('[data-filter-part-number]');if(!part){if(wrap)wrap.remove();return}if(!field){wrap=document.createElement('label');wrap.setAttribute('data-filter-part-number','true');wrap.innerHTML='Part Number<input '+context.attribute+'="filterPartNumber" readonly>';var modelInput=context.root.querySelector(context.model),anchor=modelInput&&modelInput.closest('label');if(anchor)anchor.insertAdjacentElement('afterend',wrap);field=wrap.querySelector('input')}if(field)field.value=part}
  function pmosPrepareFilterParts(root){Array.prototype.forEach.call((root||document).querySelectorAll('[data-body-field="filterModel"],[data-equipment-field="filterModel"]'),function(input){pmosSyncFilterPartNumber(input)})}
  function pmosInstallSpaOptions(card){var select=card&&card.querySelector('[data-body-field="spaType"]');if(!select)return;if(!Array.prototype.some.call(select.options,function(option){return option.value==='Attached Spa'})){var attached=document.createElement('option');attached.value='Attached Spa';attached.textContent='Attached Spa';select.insertBefore(attached,select.querySelector('option[value="Other"]'))}Array.prototype.forEach.call(select.options,function(option){if(option.value==='Spill-Over Spa'){option.value='Spillover Spa';option.textContent='Spillover Spa'}})}
  function pmosTitleCaseHeadings(root){Array.prototype.forEach.call((root||document).querySelectorAll('.body-title,.unit-title,.equipment-head>span'),function(node){var special={PH:'pH',ORP:'ORP',UV:'UV'};node.textContent=String(node.textContent||'').replace(/\b[A-Za-z][A-Za-z-]*\b/g,function(word){return special[word.toUpperCase()]||word.charAt(0).toUpperCase()+word.slice(1)})});Array.prototype.forEach.call((root||document).querySelectorAll('.chemistry-option>.check-row'),function(label){Array.prototype.forEach.call(label.childNodes,function(node){if(node.nodeType===3)node.nodeValue=node.nodeValue.replace(/chemistry automation/ig,' Chemistry Automation').replace(/equipment automation/ig,' Equipment Automation')})})}
  function pmosConfigureStandaloneBody(card){if(!card)return;var bodyType=fieldValue(card,'[data-body-field="name"]').toLowerCase(),setup=fieldValue(card,'[data-body-field="equipmentSetup"]'),standalone=bodyType==='spa'&&setup==='Self-Contained Unit',chemistry=card.querySelector('.chemistry-option'),automation=card.querySelector('.automation-option');[chemistry,automation].forEach(function(option){if(option)option.style.display=standalone?'none':''});if(!standalone)return;var chemistryToggle=card.querySelector('[data-body-field="chemistryEnabled"]'),automationToggle=card.querySelector('[data-body-field="automationEnabled"]');if(chemistryToggle&&chemistryToggle.checked){chemistryToggle.checked=false;toggleChemistryAutomation(chemistryToggle)}if(automationToggle&&automationToggle.checked){automationToggle.checked=false;toggleEquipmentAutomation(automationToggle)}var sanitization=card.querySelector('[data-body-field="sanitization"]');if(sanitization){sanitization.value='Chlorine';renderPrimarySanitizer(sanitization);var primary=card.querySelector('.primary-sanitizer-card'),make=primary&&primary.querySelector('[data-equipment-field="make"]');if(make){make.value='Floater';updateSanitizerModels(make)}}}
  function pmosPrimaryPool(card){return Array.prototype.filter.call(document.querySelectorAll('.water-body'),function(candidate){return candidate!==card&&fieldValue(candidate,'[data-body-field="name"]').toLowerCase()==='pool'})[0]||document.querySelector('.water-body')}
  function pmosSharedAutomationText(pool){if(!pool)return'Uses the Pool sanitization, circulation, heating, filtration, covers, automation, and other equipment.';var sanitation=fieldValue(pool,'[data-body-field="sanitization"]'),parts=sanitation?[sanitation]:[],chem=pool.querySelector('[data-body-field="chemistryEnabled"]'),auto=pool.querySelector('[data-body-field="automationEnabled"]');if(chem&&chem.checked)parts.push([fieldValue(pool,'[data-body-field="chemistryMake"]'),fieldValue(pool,'[data-body-field="chemistryModel"]')].filter(Boolean).join(' '));if(auto&&auto.checked)parts.push([fieldValue(pool,'[data-body-field="automationMake"]'),fieldValue(pool,'[data-body-field="automationModel"]')].filter(Boolean).join(' '));return'Uses all Pool equipment'+(parts.length?', including '+parts.join(' · '):'')+'. Only add equipment below when it is exclusive to the spa.'}
  function pmosConfigureSharedBody(card){if(!card)return;var shared=fieldValue(card,'[data-body-field="name"]').toLowerCase()==='spa'&&fieldValue(card,'[data-body-field="equipmentSetup"]')==='Shared with Pool',summary=card.querySelector('[data-pmos-shared-equipment]');if(!summary){summary=document.createElement('div');summary.className='pmos-shared-equipment-summary';summary.setAttribute('data-pmos-shared-equipment','true');var details=card.querySelector('.spa-details');if(details)details.insertAdjacentElement('afterend',summary)}var sanitization=card.querySelector('[data-body-field="sanitization"]'),sanitizationLabel=sanitization&&sanitization.closest('label'),chemistry=card.querySelector('.chemistry-option'),automation=card.querySelector('.automation-option'),host=card.querySelector('[data-chemistry-equipment-host]'),primary=card.querySelector('[data-primary-sanitizer]'),chem=card.querySelector('[data-body-field="chemistryEnabled"]'),auto=card.querySelector('[data-body-field="automationEnabled"]');[sanitizationLabel,chemistry,automation,primary].forEach(function(node){if(node)node.style.display=shared?'none':''});if(host)host.style.display=shared||!chem||!chem.checked?'none':'block';summary.classList.toggle('open',shared);if(typeof window.pmosEnsureCustomerBodyEnhancements==='function')window.pmosEnsureCustomerBodyEnhancements(card);if(typeof window.pmosConfigureSolarHeating==='function')window.pmosConfigureSolarHeating(card);if(!shared)return;var pool=pmosPrimaryPool(card);if(sanitization)sanitization.value=pool?fieldValue(pool,'[data-body-field="sanitization"]'):'';if(chem)chem.checked=false;if(auto)auto.checked=false;if(host)host.style.display='none';summary.innerHTML='<strong>All equipment shared with Pool</strong><br>'+esc(pmosSharedAutomationText(pool))}
  pmosReorderCatalogMakes();pmosCorrectFilterCatalog();
  function pmosWatchDynamicFilterFields(){if(window.__pmosFilterModelNumberObserver||!document.body)return;window.__pmosFilterModelNumberObserver=new MutationObserver(function(records){records.forEach(function(record){Array.prototype.forEach.call(record.addedNodes||[],function(node){if(node&&node.nodeType===1)pmosInstallFilterModelNumber(node.matches&&node.matches('.water-body,.equipment-card,[data-water-feature-equipment]')?node:node)})})});window.__pmosFilterModelNumberObserver.observe(document.body,{childList:true,subtree:true})}
  if(document.body)pmosWatchDynamicFilterFields();else document.addEventListener('DOMContentLoaded',pmosWatchDynamicFilterFields);
  if(typeof prepareWaterBodyOptions==='function'){var basePrepare=prepareWaterBodyOptions;prepareWaterBodyOptions=function(root){var result=basePrepare.apply(this,arguments);Array.prototype.forEach.call((root||document).querySelectorAll('.water-body'),function(card){pmosInstallBodyOverview(card);pmosInstallSpaOptions(card);pmosConfigureStandaloneBody(card);pmosConfigureSharedBody(card)});pmosInstallFilterModelNumber(root||document);pmosPrepareFilterParts(root||document);pmosShortenCartridgeLabels(root||document);pmosTitleCaseHeadings(root||document);return result}}
  if(typeof addWaterBody==='function'){var baseAddBody=addWaterBody;addWaterBody=function(){var result=baseAddBody.apply(this,arguments),cards=document.querySelectorAll('.water-body'),card=cards[cards.length-1];pmosInstallBodyOverview(card);pmosInstallSpaOptions(card);pmosInstallFilterModelNumber(card);pmosTitleCaseHeadings(card);return result}}
  if(typeof configureSpaEquipment==='function'){var baseConfigureSpa=configureSpaEquipment;configureSpaEquipment=function(card){var result=baseConfigureSpa.apply(this,arguments);pmosConfigureStandaloneBody(card);pmosConfigureSharedBody(card);return result}}
  if(typeof spaTypeChanged==='function'){var baseSpaTypeChanged=spaTypeChanged;spaTypeChanged=function(select){var result=baseSpaTypeChanged.apply(this,arguments),setup=select.closest('.water-body').querySelector('[data-body-field="equipmentSetup"]');if(/spill-?over/i.test(select.value)&&setup){setup.value='Shared with Pool';configureSpaEquipment(select.closest('.water-body'))}return result}}
  ['updateFilterModels','updateAddedFilterModels','updateWaterFeatureFilterModels'].forEach(function(name){var original=window[name];if(typeof original!=='function')return;window[name]=function(input){var result=original.apply(this,arguments),model=(pmosFilterContext(input)||{}).root;if(model){var target=model.querySelector('[data-body-field="filterModel"],[data-equipment-field="filterModel"]');if(target){pmosSyncFilterPartNumber(target);pmosSyncFilterModelNumber(target,false)}}return result}})
  document.addEventListener('input',function(event){var field=event.target&&event.target.getAttribute&&(event.target.getAttribute('data-body-field')||event.target.getAttribute('data-equipment-field'));if(['filterMake','filterType','filterModel'].indexOf(field)>=0){pmosSyncFilterPartNumber(event.target);pmosSyncFilterModelNumber(event.target,false)}});
  document.addEventListener('input',function(event){var field=event.target&&event.target.getAttribute&&event.target.getAttribute('data-body-field');if(['chemistryEnabled','chemistryMake','chemistryModel','automationEnabled','automationMake','automationModel'].indexOf(field)<0)return;Array.prototype.forEach.call(document.querySelectorAll('.water-body'),pmosConfigureSharedBody)});
  document.addEventListener('change',function(event){var field=event.target&&event.target.getAttribute&&event.target.getAttribute('data-body-field');if(['chemistryEnabled','automationEnabled','equipmentSetup','spaType'].indexOf(field)<0)return;Array.prototype.forEach.call(document.querySelectorAll('.water-body'),pmosConfigureSharedBody)});
  if(typeof addEquipment==='function'){var baseAddEquipmentForFilterParts=addEquipment;addEquipment=function(bodyCard,type,defaults){var result=baseAddEquipmentForFilterParts.apply(this,arguments),cards=bodyCard.querySelectorAll('.equipment-card[data-equipment-type="'+String(type||'')+'"]'),card=cards[cards.length-1],model=card&&card.querySelector('[data-equipment-field="filterModel"]');if(card)pmosInstallFilterModelNumber(card);if(model)pmosSyncFilterPartNumber(model,defaults&&defaults.partNumber);if(card){pmosShortenCartridgeLabels(card);pmosTitleCaseHeadings(card)}return result}}
  if(typeof addWaterFeatureEquipment==='function'){var baseAddWaterFeatureEquipmentForParts=addWaterFeatureEquipment;addWaterFeatureEquipment=function(select){var result=baseAddWaterFeatureEquipmentForParts.apply(this,arguments),card=select.closest('.equipment-card'),models=card.querySelectorAll('[data-water-feature-equipment] [data-equipment-field="filterModel"]'),model=models[models.length-1];if(card)pmosInstallFilterModelNumber(card);if(model)pmosSyncFilterPartNumber(model);if(card){pmosShortenCartridgeLabels(card);pmosTitleCaseHeadings(card)}return result}}
  if(typeof collectWaterBodies==='function'){var baseCollect=collectWaterBodies;collectWaterBodies=function(){var bodies=baseCollect.apply(this,arguments)||[],cards=document.querySelectorAll('.water-body');Array.prototype.forEach.call(cards,function(card,index){if(!bodies[index])return;var shared=fieldValue(card,'[data-body-field="name"]').toLowerCase()==='spa'&&fieldValue(card,'[data-body-field="equipmentSetup"]')==='Shared with Pool';bodies[index].shape=fieldValue(card,'[data-body-field="shape"]');bodies[index].volume=fieldValue(card,'[data-body-field="volume"]');bodies[index].filter=bodies[index].filter||{};bodies[index].filter.modelNumber=fieldValue(card,'[data-body-field="filterModelNumber"]');if(shared){var primary=card.querySelector('[data-primary-sanitizer]'),primaryType=primary&&primary.getAttribute('data-equipment-type'),removedPrimary=false;bodies[index].sanitization='';bodies[index].pump={};bodies[index].filter={};bodies[index].heater={};bodies[index].cover={};bodies[index].equipment=(bodies[index].equipment||[]).filter(function(item){if(item.type==='CHEMISTRY_AUTOMATION'||item.type==='EQUIPMENT_AUTOMATION')return false;if(!removedPrimary&&primaryType&&item.type===primaryType){removedPrimary=true;return false}return true})}});return bodies}}
  if(typeof hydrateBodies==='function'){var baseHydrate=hydrateBodies;hydrateBodies=function(bodies){var result=baseHydrate.apply(this,arguments),rows=bodies||[],cards=document.querySelectorAll('.water-body');Array.prototype.forEach.call(cards,function(card,index){pmosInstallBodyOverview(card);pmosInstallSpaOptions(card);pmosInstallFilterModelNumber(card);var body=rows[index]||{},shape=card.querySelector('[data-body-field="shape"]'),volume=card.querySelector('[data-body-field="volume"]'),filterModel=card.querySelector('[data-body-field="filterModel"]'),filterModelNumber=card.querySelector('[data-body-field="filterModelNumber"]');if(shape)shape.value=body.shape||'';if(volume)pmosSetVolumeValue(volume,body.volume||'');if(filterModelNumber)filterModelNumber.value=body.filter&&body.filter.modelNumber||'';if(filterModel)pmosSyncFilterPartNumber(filterModel,body.filter&&body.filter.partNumber);pmosConfigureStandaloneBody(card);pmosTitleCaseHeadings(card)});return result}}
})();
`;
  };
})();
