/** Shared compact equipment-profile cards for both Sheets and the Web App. */
function pmosCustomerEquipmentProfileStyles_() {
  return String.raw`
.pmos-body-profile{margin:0 0 14px;padding:14px;border:1px solid var(--border,#d2dade);border-radius:12px;background:var(--surface-soft,#f4f7f8)}
.pmos-body-profile-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:11px}.pmos-body-profile-title{margin:0;color:var(--text,#293944);font-size:16px;font-weight:900}.pmos-body-meta{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:6px}.pmos-body-chip{padding:4px 8px;border:1px solid #b8c7ce;border-radius:999px;background:#dce8ed;color:#111;font-size:10px;font-weight:900}.pmos-body-relation{color:var(--muted,#68747a);font-size:11px;font-weight:700}
.pmos-equipment-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;align-items:start}.pmos-equipment-grid.pmos-three-columns{grid-template-columns:repeat(3,minmax(0,1fr))}.pmos-profile-card{position:relative;align-self:start;min-width:0;border:1px solid var(--border,#d2dade);border-radius:9px;background:#fff;overflow:hidden}.pmos-profile-card.pmos-wide{grid-column:1/-1}.pmos-profile-card>summary{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;min-height:64px;padding:11px 38px 11px 12px;list-style:none;cursor:default}.pmos-profile-card.pmos-expandable>summary{cursor:pointer}.pmos-profile-card>summary::-webkit-details-marker{display:none}.pmos-card-copy{min-width:0;max-width:100%}.pmos-card-heading{color:var(--muted,#68747a);font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.pmos-card-subject{display:flex;align-items:baseline;gap:6px;min-width:0;margin-top:5px;color:var(--text,#293944);font-size:12px;font-weight:900;line-height:1.35;white-space:nowrap}.pmos-card-subject-text{min-width:0;overflow:hidden;text-overflow:ellipsis}.pmos-card-number{display:inline-flex;flex:0 0 auto;align-items:center;gap:3px;margin:0;border:0;background:transparent;color:var(--muted,#68747a);font:inherit;font-size:9px;font-weight:700;white-space:nowrap;cursor:pointer;vertical-align:baseline}.pmos-card-number:hover{color:var(--brand-dark,#0f5470)}.pmos-number-kind{font-size:8px;text-transform:uppercase}.pmos-copy-icon{font-size:11px;line-height:1}.pmos-card-chevron{position:absolute;top:12px;right:12px;color:var(--brand-dark,#0f5470);font-size:14px;font-weight:900;transition:transform .15s}.pmos-profile-card[open] .pmos-card-chevron{transform:rotate(180deg)}.pmos-card-detail{padding:0 12px 12px;color:var(--text,#293944);font-size:11px;line-height:1.45}.pmos-card-detail-line{display:flex;align-items:center;justify-content:space-between;gap:8px;padding-top:9px;border-top:1px solid var(--border,#d2dade)}
.pmos-table-card[open] .pmos-card-subject{display:none}.pmos-equipment-table{display:grid;grid-template-columns:minmax(120px,.75fr) minmax(180px,1.6fr) minmax(95px,.65fr);gap:0;border-top:1px solid var(--border,#d2dade)}.pmos-equipment-table-head,.pmos-equipment-table-row{display:contents}.pmos-equipment-table span{min-width:0;padding:7px 8px;border-bottom:1px solid #e6ecef;word-break:break-word}.pmos-equipment-table-head span{color:var(--muted,#68747a);font-size:9px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.pmos-equipment-table-row span{font-size:10px}.pmos-equipment-table .pmos-table-number{display:flex;align-items:flex-start;gap:4px}.pmos-equipment-note{grid-column:1/-1;padding:11px 12px;border:1px solid var(--border,#d2dade);border-radius:9px;background:#fff;color:var(--text,#293944);font-size:11px;white-space:pre-wrap}.pmos-copy-status{position:fixed;z-index:99999;right:18px;bottom:18px;padding:8px 11px;border-radius:7px;background:#293944;color:#fff;font-size:11px;box-shadow:0 4px 14px rgba(0,0,0,.2)}
@media(max-width:760px){.pmos-body-profile-head{align-items:flex-start;flex-direction:column}.pmos-body-meta{justify-content:flex-start}.pmos-equipment-grid{grid-template-columns:1fr}.pmos-profile-card.pmos-wide{grid-column:auto}.pmos-equipment-table{grid-template-columns:minmax(95px,.8fr) minmax(130px,1.4fr) minmax(75px,.7fr)}}`;
}

function pmosCustomerEquipmentProfileClientScript_() {
  return String.raw`
(function(){
  window.__pmosEquipmentProfileCardsLoaded=true;
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
  function arr(value){return Array.isArray(value)?value:[]}
  function details(item){return item&&item.details&&typeof item.details==='object'?item.details:(item||{})}
  function title(value){var special={PH:'pH',ORP:'ORP',UV:'UV'};return String(value||'').replace(/_/g,' ').replace(/\b([A-Za-z][A-Za-z-]*)\b/g,function(word){return special[word.toUpperCase()]||word.charAt(0).toUpperCase()+word.slice(1).toLowerCase()})}
  function label(type){var labels={CHEMISTRY_AUTOMATION:'Chemistry Automation',EQUIPMENT_AUTOMATION:'Equipment Automation',ACID_TANK:'Acid Tank',CHLORINE_TANK:'Chlorine Tank',PH_PROBE:'pH Probe',ORP_PROBE:'ORP Probe',FLOW_CELL:'Flow Cell',SOLAR_BOOSTER_PUMP:'Solar Booster Pump',SOLAR_VALVE_ACTUATOR:'Solar Valve Actuator',SOLAR_AUTOMATION:'Solar Automation',SALT_SYSTEM:'Salt Cell',CHLORINE_FEEDER:'Chlorinator',BROMINE_FEEDER:'Brominator',WATER_FEATURE:'Water Feature',OTHER_SANITIZER:'Other Sanitizer',OZONATOR:'Ozonator',UV:'UV Light',ROBOT:'Robot',PUMP:'Pump',FILTER:'Filter',HEATER:'Heater'};return labels[type]||title(type||'Equipment')}
  function compact(values,separator){return values.filter(function(value){return value!=null&&String(value).trim()}).join(separator||' · ')}
  function rawNumber(value){return String(value==null?'':value).trim().replace(/^(?:model(?:\s*(?:number|#))?|m\/n|part(?:\s*(?:number|#))?|p\/n)\s*[:#-]?\s*/i,'')}
  function numberButton(value,kind){var clean=rawNumber(value);if(!clean)return'';var shortKind=kind==='Model Number'?'Model':'P/N';return '<button type="button" class="pmos-card-number" data-pmos-copy="'+esc(clean)+'" title="Copy '+esc(kind||'number')+'"><span class="pmos-number-kind">'+shortKind+'</span><span class="pmos-number-value">'+esc(clean)+'</span><span class="pmos-copy-icon" aria-hidden="true">⧉</span></button>'}
  function simpleCard(heading,subject,detail,number,numberKind,wide,detailNumber,detailNumberKind){var expandable=!!(detail||detailNumber),subjectHtml=subject||number?'<div class="pmos-card-subject"><span class="pmos-card-subject-text">'+esc(subject||'')+'</span>'+numberButton(number,numberKind)+'</div>':'';return '<details class="pmos-profile-card'+(wide?' pmos-wide':'')+(expandable?' pmos-expandable':'')+'"><summary><div class="pmos-card-copy"><div class="pmos-card-heading">'+esc(heading)+'</div>'+subjectHtml+'</div>'+(expandable?'<span class="pmos-card-chevron" aria-hidden="true">⌄</span>':'')+'</summary>'+(expandable?'<div class="pmos-card-detail"><div class="pmos-card-detail-line"><span>'+esc(detail||'')+'</span>'+numberButton(detailNumber,detailNumberKind)+'</div></div>':'')+'</details>'}
  function tableCard(heading,subject,rows){rows=arr(rows).filter(function(row){return row&&row[1]});var table='<div class="pmos-equipment-table"><div class="pmos-equipment-table-head"><span>Equipment</span><span>Make &amp; Model</span><span>Number</span></div>'+rows.map(function(row){var number=row[2]||'',kind=row[3]||'Part Number';return '<div class="pmos-equipment-table-row"><span>'+esc(row[0])+'</span><span>'+esc(row[1])+'</span><span class="pmos-table-number">'+(number?numberButton(number,kind):'—')+'</span></div>'}).join('')+'</div>';return '<details class="pmos-profile-card pmos-wide pmos-expandable pmos-table-card"><summary><div class="pmos-card-copy"><div class="pmos-card-heading">'+esc(heading)+'</div>'+(subject?'<div class="pmos-card-subject">'+esc(subject)+'</div>':'')+'</div><span class="pmos-card-chevron" aria-hidden="true">⌄</span></summary>'+table+'</details>'}
  function parsedModel(value){var raw=String(value||''),match=raw.match(/^([^()]+?)\s*(?:\(([^)]+)\))?$/);return{model:match?match[1].trim():raw.trim(),detail:match&&match[2]?match[2].trim():''}}
  function filterCard(unit){unit=unit||{};if(!compact([unit.make,unit.type,unit.model,unit.modelNumber]))return'';var parsed=parsedModel(unit.model),code=unit.modelNumber||(parsed.model.match(/\b(?:SD|TR|CCP?|FNSP|SFTM|S\d|C\d|DE\d)[A-Z0-9.-]*\b/i)||[])[0]||parsed.model,sd60=/^SD60$/i.test(code),family=compact([unit.make,unit.type?title(unit.type)+' Filter':'Filter'],' '),subject=compact([family,code]),detail=parsed.detail?parsed.detail.replace(/\b22(?:\.5|\.0)?\s*in(?:ch(?:es)?)?\b/i,'22.5\" Diameter').replace(/\b250\s*lb\b/i,'250 lb Sand'):'',part=unit.partNumber||(sd60&&String(unit.make||'').toLowerCase()==='pentair'?'145322':''),replacement=unit.cartridgeSetNumber||unit.replacementCartridgePartNumber||'';if(sd60&&!detail)detail='22.5\" Diameter · 250 lb Sand';if(replacement)detail=compact([detail,'Replacement Cartridge']);return simpleCard('Filter',subject,detail,part,'Part Number',false,replacement,'Part Number')}
  function pumpCard(unit){unit=unit||{};if(!compact([unit.make,unit.model]))return'';var detail='',model=String(unit.model||'').replace(/\s*\([^)]*\)\s*$/,'').trim();if(/superflo\s+vst/i.test(model))detail='Variable Speed · Up to 1.5 HP · 115–230 V';return simpleCard('Pump',compact([unit.make,model],' '),detail,unit.partNumber||unit.modelNumber,unit.partNumber?'Part Number':'Model Number',false)}
  function heaterCard(unit){unit=unit||{};if(!compact([unit.make,unit.model,unit.type]))return'';var model=String(unit.model||''),capacity=(model.match(/\b(125|175|200|250|300|400)\b/)||[])[1],clean=model.replace(/\s+\b(125|175|200|250|300|400)\b.*$/,'').trim(),detail=compact([unit.type,capacity?Number(capacity).toLocaleString() + ',000 BTU':'']);return simpleCard('Heater',compact([unit.make,clean||model],' '),detail,unit.partNumber||unit.modelNumber,unit.partNumber?'Part Number':'Model Number',false)}
  function solarHeatingCard(unit){unit=unit||{};var rows=arr(unit.solarEquipment).map(function(item){var name={BOOSTER_PUMP:'Pump',FILTER:'Filter',VALVE_ACTUATOR:'Valve Actuator',CONTROLLER:'Solar-Specific Controller',OTHER:'Other Equipment'}[item.type]||'Solar Equipment',subject=compact([item.make,item.model,item.notes]),number=item.partNumber||item.modelNumber||'';return[name,subject,number,item.partNumber?'Part Number':'Model Number']}).filter(function(row){return row[1]||row[2]});var connected=unit.connectedToEquipmentAutomation?'Connected to Equipment Automation':'';if(rows.length)return tableCard('Solar Heating',connected,rows);return connected?simpleCard('Solar Heating',connected,'','','',false):simpleCard('Heater','Solar','','','',false)}
  function coverCard(unit){unit=unit||{};var subject=compact([unit.type,unit.winterType]);return subject?simpleCard('Cover',subject,'','','',false):''}
  function itemSubject(item){var d=details(item),type=item.type||'';return compact([d.make||d.manufacturer,d.model||d.filterModel||d.sanitizerType||d.equipmentType,d.purpose])||label(type)}
  function sanitizerCard(body,items){var types=['SALT_SYSTEM','CHLORINE_FEEDER','BROMINE_FEEDER','IONIZER','OZONATOR','UV','OTHER_SANITIZER'],rows=[];items.forEach(function(item){if(types.indexOf(item.type)<0)return;var d=details(item),number=d.partNumber||d.modelNumber||'';rows.push([label(item.type),compact([d.make||d.manufacturer,d.model||d.sanitizerType])||body.sanitization||label(item.type),number,d.partNumber?'Part Number':'Model Number'])});if(!rows.length&&body.sanitization)rows.push(['Primary Sanitizer',body.sanitization,'','']);return rows.length?tableCard('Primary Sanitization',compact([body.sanitization,rows.map(function(row){return row[1]}).filter(Boolean)[0]]),rows):''}
  function chemistryCard(item){if(!item)return'';var d=details(item),rows=[],keys=[['Controller','controller'],['Configuration','configuration'],['Flow Cell','flowCell'],['pH Probe','phProbe'],['ORP Probe','orpProbe'],['Acid Tank','acidTank'],['Acid Pump Motor','acidPumpMotor'],['Pump Head','pumpHead'],['Chlorine Tank','chlorineTank'],['Chlorine Pump Motor','chlorinePumpMotor'],['Chlorine Pump Head','chlorinePumpHead']];keys.forEach(function(pair){var model=d[pair[1]+'Model'],part=d[pair[1]+'PartNumber'];if(model||part)rows.push([pair[0],compact([d.make||d.manufacturer,model]),part,'Part Number'])});if(!rows.length)rows.push(['System',compact([d.make||d.manufacturer,d.model])||'Chemistry Automation',d.partNumber||d.modelNumber,d.partNumber?'Part Number':'Model Number']);return tableCard('Chemistry Automation',compact([d.make||d.manufacturer,d.model]),rows)}
  function featureRows(d){var rows=[],parsed=arr(d.featureEquipment);if(!parsed.length){try{parsed=JSON.parse(d.featureEquipmentJson||'[]')}catch(ignore){parsed=[]}}arr(parsed).forEach(function(item){var x=details(item),prefix=item.type==='PUMP'?'pump':item.type==='FILTER'?'filter':item.type==='HEATER'?'heater':'featureEquipment',number=x[prefix+'PartNumber']||x[prefix+'ModelNumber']||x.partNumber||x.modelNumber||'',subject=compact([x[prefix+'Make']||x.make,x[prefix+'Model']||x.model]);rows.push([label(item.type),subject||label(item.type),number,(x[prefix+'PartNumber']||x.partNumber)?'Part Number':'Model Number'])});if(d.actuatorMake||d.actuatorModel||d.actuatorModelNumber){var actuatorNumber=d.actuatorPartNumber||d.actuatorModelNumber,knownPart=/^(263043|263044|263045|521485)$/.test(String(actuatorNumber||''));rows.push(['Valve Actuator',compact([d.actuatorMake,d.actuatorModel]),actuatorNumber,d.actuatorPartNumber||knownPart?'Part Number':'Model Number'])}return rows}
  function relationship(body,index,all){var type=String(body.type||body.name||'').toLowerCase(),spaType=String(body.spaType||''),setup=String(body.equipmentSetup||'');if(type.indexOf('spa')>=0){if(/spill-?over/i.test(spaType))return'Spillover';if(/attached/i.test(spaType))return'Attached Spa';if(setup==='Shared with Pool')return'Equipment Shared with Pool';return''}var spas=arr(all).filter(function(candidate){return /spa/i.test(String(candidate.type||candidate.name||''))});if(spas.some(function(spa){return /spill-?over/i.test(String(spa.spaType||''))}))return'Spillover';if(spas.some(function(spa){return /attached/i.test(String(spa.spaType||''))}))return'Attached Spa';if(spas.some(function(spa){return String(spa.equipmentSetup||'')==='Shared with Pool'}))return'Equipment Shared with Spa';return''}
  function renderBody(body,index,all){body=body||{};var items=arr(body.equipment),used={CHEMISTRY_AUTOMATION:true,FLOW_CELL:true,ACID_TANK:true,CHLORINE_TANK:true,PH_PROBE:true,ORP_PROBE:true,SALT_SYSTEM:true,CHLORINE_FEEDER:true,BROMINE_FEEDER:true,IONIZER:true,OZONATOR:true,UV:true,OTHER_SANITIZER:true,WATER_FEATURE:true},chem=items.filter(function(item){return item.type==='CHEMISTRY_AUTOMATION'})[0],automation=items.filter(function(item){return item.type==='EQUIPMENT_AUTOMATION'})[0],features=items.filter(function(item){return item.type==='WATER_FEATURE'}),cards='';cards+=pumpCard(body.pump);cards+=filterCard(body.filter);cards+=/^solar$/i.test(String(body.heater&&body.heater.type||''))?solarHeatingCard(body.heater):heaterCard(body.heater);cards+=coverCard(body.cover);if(automation){var ad=details(automation);cards+=simpleCard('Equipment Automation',compact([ad.manufacturer||ad.make,ad.model]),compact([ad.controller,ad.connectedTo]),ad.partNumber||ad.modelNumber,ad.partNumber?'Part Number':'Model Number',false);used.EQUIPMENT_AUTOMATION=true}cards+=sanitizerCard(body,items);cards+=chemistryCard(chem);features.forEach(function(item){var d=details(item),feature=title(d.featureType||d.name||'Water Feature'),rows=featureRows(d),heading='Water Feature: '+feature,featureDetail=compact([d.location,d.controlMethod||d.automation]);if(rows.length)cards+=tableCard(heading,featureDetail,rows);else cards+=simpleCard(heading,featureDetail,'','','',true)});items.forEach(function(item){if(used[item.type])return;var d=details(item),extra=compact([d.connectedTo,d.quantity?('Quantity '+d.quantity):'',d.notes]),number=d.partNumber||d.modelNumber||d.filterModelNumber,replacement=item.type==='FILTER'&&(d.cartridgeSetNumber||d.replacementCartridgePartNumber)||'';if(replacement)extra=compact([extra,'Replacement Cartridge']);cards+=simpleCard(label(item.type),itemSubject(item),extra,number,d.partNumber?'Part Number':'Model Number',false,replacement,'Part Number')});if(body.equipmentNotes)cards+='<div class="pmos-equipment-note"><strong>Equipment Notes</strong><br>'+esc(body.equipmentNotes)+'</div>';var meta='';if(body.shape)meta+='<span class="pmos-body-chip">'+esc(title(body.shape))+'</span>';if(body.volume)meta+='<span class="pmos-body-chip">'+esc(body.volume)+'</span>';var relation=relationship(body,index,all);if(relation)meta+='<span class="pmos-body-relation">'+esc(relation)+'</span>';return '<section class="pmos-body-profile"><div class="pmos-body-profile-head"><h4 class="pmos-body-profile-title">'+esc(title(body.name||body.type||('Body '+(index+1))))+'</h4><div class="pmos-body-meta">'+meta+'</div></div><div class="pmos-equipment-grid" data-pmos-adaptive-grid>'+cards+'</div></section>'}
  function renderProfiles(bodies){bodies=arr(bodies);return bodies.map(function(body,index){return renderBody(body,index,bodies)}).join('')}
  function copyFallback(value){var area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.cssText='position:fixed;left:-9999px;top:0';document.body.appendChild(area);area.select();var ok=false;try{ok=document.execCommand('copy')}catch(ignore){}if(!ok){area.style.cssText='position:fixed;left:12px;bottom:12px;z-index:100000;width:240px;height:44px';area.removeAttribute('readonly');area.focus();area.select()}else area.remove();return ok}
  function announce(value,ok){var old=document.querySelector('.pmos-copy-status');if(old)old.remove();var note=document.createElement('div');note.className='pmos-copy-status';note.textContent=ok?'Copied '+value:'Copy selected — press Ctrl+C';document.body.appendChild(note);setTimeout(function(){if(note.parentNode)note.remove()},1800)}
  function fitGrid(grid){if(!grid)return;grid.classList.remove('pmos-three-columns');if(!grid.closest('#view-customers')||grid.clientWidth<760)return;grid.classList.add('pmos-three-columns');var cards=grid.querySelectorAll('.pmos-profile-card:not(.pmos-wide)'),tooTight=false;Array.prototype.forEach.call(cards,function(card){var copy=card.querySelector('.pmos-card-copy'),subject=card.querySelector('.pmos-card-subject'),text=card.querySelector('.pmos-card-subject-text');if((copy&&copy.scrollWidth>copy.clientWidth+1)||(subject&&subject.scrollWidth>subject.clientWidth+1)||(text&&text.scrollWidth>text.clientWidth+1))tooTight=true});if(tooTight)grid.classList.remove('pmos-three-columns')}
  function fitAll(){Array.prototype.forEach.call(document.querySelectorAll('[data-pmos-adaptive-grid]'),fitGrid)}
  document.addEventListener('click',function(event){var target=event.target&&event.target.closest&&event.target.closest('[data-pmos-copy]');if(!target){var fixed=event.target&&event.target.closest&&event.target.closest('.pmos-profile-card:not(.pmos-expandable)>summary');if(fixed)event.preventDefault();return}event.preventDefault();event.stopPropagation();var value=rawNumber(target.getAttribute('data-pmos-copy')||''),fallback=function(){var ok=copyFallback(value);announce(value,ok)};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(value).then(function(){announce(value,true)},fallback);else fallback()});
  window.pmosRenderEquipmentProfile=renderBody;window.pmosRenderEquipmentProfiles=renderProfiles;
  if(window.addEventListener)window.addEventListener('resize',fitAll);function watchProfiles(){if(!document.body)return;if(typeof MutationObserver==='function')new MutationObserver(function(){requestAnimationFrame(fitAll)}).observe(document.body,{childList:true,subtree:true});fitAll()}if(document.body)watchProfiles();else if(document.addEventListener)document.addEventListener('DOMContentLoaded',watchProfiles,{once:true});
  if(typeof bodyHtml==='function')bodyHtml=function(body,index,all){return renderBody(body,index,all||[])};
})();`;
}

function pmosInjectCustomerEquipmentProfileUi_(html) {
  let output = String(html || '');
  if (output.indexOf('__pmosEquipmentProfileCardsLoaded') >= 0) return output;
  output = output.replace('</style></head>', pmosCustomerEquipmentProfileStyles_() + '\n</style></head>');
  output = output.replace('</script></body></html>', pmosCustomerEquipmentProfileClientScript_() + '\n</script></body></html>');
  return output;
}

(function () {
  if (typeof buildPmosCustomerAccountLookupHtml_ !== 'function') return;
  const baseBuildLookup = buildPmosCustomerAccountLookupHtml_;
  buildPmosCustomerAccountLookupHtml_ = function(mode, initialCustomerId) {
    return pmosInjectCustomerEquipmentProfileUi_(baseBuildLookup(mode, initialCustomerId));
  };
})();
