#!/usr/bin/env python3
"""Static regression contract for PMOS customer/account/service-location workflows."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8")


def require(text: str, needle: str, label: str, failures: list[str]) -> None:
    if needle not in text:
        failures.append(f"missing {label}: {needle}")


def forbid(text: str, needle: str, label: str, failures: list[str]) -> None:
    if needle in text:
        failures.append(f"unexpected {label}: {needle}")


def ordered(text: str, needles: list[str], label: str, failures: list[str]) -> None:
    positions = [text.find(needle) for needle in needles]
    if any(position < 0 for position in positions) or positions != sorted(positions):
        failures.append(f"incorrect {label}: {' -> '.join(needles)}")


def main() -> None:
    failures: list[str] = []
    index = read("Index.html")
    client = read("Client.html")
    add = read("Web_Add_Customer.html")
    maintenance = read("Web_Add_Maintenance.html")
    editor = read("Web_Customer_Edit.html")
    location = read("Web_Add_Service_Location.html")
    profile = read("Web_Customers.html")
    account_contacts = read("24-Q_Customer_Account_Contacts.gs")
    location_contacts = read("24-O_Customer_Service_Location_Contacts.gs")
    billing = read("24-P_Customer_Account_Contact_Addresses.gs")
    shared_equipment = read("24-F_Customer_Equipment_Editor_Component.gs")
    equipment_enhancements = read("24-U_Customer_Equipment_Enhancements.gs")
    equipment = read("24-T_Customer_Form_Enhancements.gs")
    equipment_fixes = read("24-U_Customer_Form_Enhancement_Fixes.gs")
    maintenance_contacts = read("24-X_Add_Maintenance_Contacts.gs")
    maintenance_transaction = read("20-E_Add_Maintenance_Customer_Transaction.gs")
    sheets_maintenance = read("20-C_Add_Maintenance_Client_UI.gs")
    sheets_locations = read("24-K_Customer_Account_Service_Locations_UI.gs")
    account_model = read("24-I_Customer_Account_Service_Locations.gs")
    account_editor = read("24-L_Customer_Profile_Account_Integration.gs")
    customer_editor = read("24-E_Customer_Editor.gs")
    water = read("24-S_Customer_Water_Maintenance_Editor.gs")
    context_notes = read("24-V_Customer_Context_Notes.gs")
    notes_bridge = read("24-W_Customer_Context_Notes_UI.gs")
    sheets_add_customer = read("Sheets_Add_Customer.html")
    sheets_add_customer_server = read("24-R1_Add_Customer_Sheets_Parity.gs")
    lifecycle = read("24-Z_Customer_Profile_Editor_Lifecycle.gs")
    lifecycle_runtime = read("24-ZZZ_Customer_Lifecycle_Runtime_Bridge.gs")
    sheets_editor_lifecycle = read("24-ZZZZZZ_Sheets_Account_Contact_Lifecycle_UI.gs")
    legacy_contact_bridge = read("24-ZZZZZZZ_Legacy_Account_Contact_Bridge.gs")

    ordered(index, ["Customer Look-Up", "Add Customer", "Add Maintenance Client"], "Customers menu order", failures)
    ordered(index, ["Temporary Maintenance", "Service Call", "Opening / Closing"], "Scheduling menu order", failures)
    require(index, "pmosRouteRecommendationCardStyles_()", "shared route-card styles", failures)
    require(index, "pmosRouteRecommendationCardScript_()", "shared route-card script", failures)
    require(index, "pmosOpenCustomerProfile(customerId)", "direct created-customer profile handoff", failures)
    forbid(index, "search.value=customerId", "Customer-ID search workaround for profile handoff", failures)
    require(client, "function routeData(value)", "null-safe Web route payload normalizer", failures)
    require(client, "state.data=routeData(data)", "normalized Web startup route data", failures)

    require(add, "Customer Contact Info", "combined customer-contact card", failures)
    forbid(add, "Customer Identity", "separate Customer Identity card", failures)
    require(add, "last+' Residence'", "Last Name Residence default", failures)
    require(add, "formatName($('acLastName'))", "last-name capitalization", failures)
    require(add, "formatName($('acFirstName'))", "first-name capitalization", failures)
    require(add, "formatPhone($('acPhone'))", "primary-phone formatting", failures)
    require(add, "+ Add Account Contact", "Add Account Contact control", failures)
    ordered(add, ["acAccountContacts", "acAddAccountContact", "acBillingHost"], "billing address below Account Contacts card", failures)
    require(add, "+ Add Service Location Contact", "Add Service Location Contact control", failures)
    require(add, "+ Add Body of Water", "Add Body of Water wording", failures)
    forbid(add, "Add Another Body of Water", "old body button wording", failures)
    require(add, "?'Finishing…':'Creating…'", "Create Customer working state", failures)
    require(add, "createPmosCustomerAccountRuntime", "account-aware create endpoint", failures)
    require(add, "savePrimaryBeforeAdditionalLocation", "save primary location before opening another location", failures)
    require(add, "Primary service location saved. Opening a new service-location form", "saved-location handoff status", failures)
    forbid(add, "options.draft=true", "unsaved nested additional-location draft workflow", failures)
    require(add, "ac-invalid-marker", "field-level invalid-entry feedback", failures)
    require(add, "pmosBillingAddressIsConfirmed('acBilling')", "confirmed billing-address validation", failures)
    require(add, "acMaintenance", "primary-location Water Maintenance toggle", failures)
    require(add, "id=\"acMaintenanceStatus\"", "primary-location Maintenance Status selector", failures)
    require(add, "status:maintenance?$('acMaintenanceStatus').value:''", "primary-location status payload", failures)
    require(add, "acMaintenanceNotes", "conditional primary Maintenance Notes", failures)
    ordered(add, ["acClosingNotes", "acAddServiceLocationButton", "acAdditionalLocationHost"], "primary notes before additional locations", failures)
    require(add, "Press Shift+Enter to add a new line", "notes keyboard guidance", failures)
    for label in ("Entry Information", "General Notes", "Opening Notes", "Closing Notes"):
        require(add, label, f"Add Customer {label}", failures)
    require(sheets_add_customer_server, "createTemplateFromFile('Sheets_Add_Customer')", "shared Sheets Add Customer template", failures)
    require(sheets_add_customer_server, ".setWidth(1180)", "large Sheets Add Customer width", failures)
    require(sheets_add_customer_server, ".setHeight(860)", "large Sheets Add Customer height", failures)
    require(sheets_add_customer, "include('Web_Add_Customer')", "Web/Sheets Add Customer form parity", failures)
    require(sheets_add_customer, "include('Web_Add_Service_Location')", "Web/Sheets inline service-location parity", failures)
    require(sheets_add_customer, ".showPmosCustomerAccountLookupRuntime(customerId)", "runtime Sheets profile handoff", failures)

    require(maintenance, "amMaintenanceNotes", "maintenance-form Maintenance Notes", failures)
    require(maintenance, "id=\"amMaintenanceStatus\"", "Web maintenance-create status selector", failures)
    require(maintenance, "status:$('amMaintenanceStatus').value", "Web maintenance-create status payload", failures)
    require(maintenance, "amAccountContacts", "maintenance Account Contacts", failures)
    require(maintenance, "amLocationContacts", "maintenance Service Location Contacts", failures)
    require(maintenance, "amBillingHost", "maintenance account billing address", failures)
    require(maintenance, "pmosCollectAccountContacts('amAccountContacts')", "maintenance Account Contact payload", failures)
    require(maintenance, "pmosCollectLocationContacts('amLocationContacts')", "maintenance Service Location Contact payload", failures)
    require(maintenance, "am-hidden", "hidden manual placement", failures)
    require(maintenance, "Hide Manual Placement", "manual placement toggle state", failures)
    require(maintenance, "inlineHostId:'amAdditionalLocationHost'", "inline maintenance location editor", failures)
    require(maintenance, "Creating the maintenance client", "maintenance create working state", failures)

    require(editor, "ce-toggle-track", "sliding Water Maintenance toggle", failures)
    require(editor, "maintenanceRemovalConfirmed", "pending maintenance-removal confirmation", failures)
    require(editor, "Saving…", "editor save working state", failures)
    require(editor, "inlineHostId:'ceAdditionalLocationHost'", "inline editor location form", failures)
    require(editor, "classList.add('ce-loading')", "Web editor loading gate", failures)
    require(editor, "finishLoading()", "Web editor reveal after complete hydration", failures)
    require(editor, "<label class=\"ce-full\">Maintenance Notes<textarea id=\"ceMaintenanceNotes\"", "Maintenance Notes in maintenance section", failures)
    for form in (maintenance, editor, location):
        require(form, "pmosRouteRecommendationHtml", "shared detailed route cards", failures)

    require(location, "sl-toggle-track", "added-location sliding maintenance toggle", failures)
    require(location, "id=\"slMaintenanceStatus\"", "Web added-location status selector", failures)
    require(location, "status:maintenance?$('slMaintenanceStatus').value:''", "Web added-location status payload", failures)
    require(location, "slMaintenanceNotesWrap", "conditional added-location Maintenance Notes", failures)
    require(location, "toggleMaintenanceSafely", "failure-contained added-location maintenance toggle", failures)
    require(location, "event.stopPropagation", "isolated added-location maintenance toggle", failures)
    require(location, "backdrop.classList.add('open')", "added-location form visibility recovery", failures)
    require(profile, ".customer-primary-contact-badge.location", "blue service-location contact label", failures)
    require(profile, ".customer-primary-contact-badge.additional", "additional-contact label color", failures)
    require(profile, "<h3>Contacts</h3>", "single combined Contacts section", failures)
    require(profile, "customer-contact-note", "expandable contact notes", failures)
    require(profile, ".customer-contact-card,.customer-contact-card.primary", "uniform contact-card background override", failures)
    require(location, "this service-location form and its information are still intact", "maintenance-toggle recovery message", failures)
    require(location, "state.draft", "unsaved additional-location draft mode", failures)
    require(location, "Keep Service Location", "draft location completion control", failures)
    require(location, "sl-invalid-marker", "added-location invalid-entry feedback", failures)
    forbid(location, "slEquipmentNotes", "duplicate location-level Equipment Notes", failures)
    require(location, "if(id&&!wasInline)", "nested location stays in parent editor", failures)
    require(profile, "inlineHostId:'customerInlineLocationHost'", "inline profile location form", failures)
    forbid(profile, "if(profile.equipmentNotes)items.push", "duplicate profile-level Equipment Notes", failures)

    require(account_contacts, "Last name</label><input data-account-contact=\"lastName\"", "Account Contact last-name-first layout", failures)
    require(location_contacts, "Last name</label><input data-location-contact=\"lastName\"", "Service Location Contact last-name-first layout", failures)
    require(account_contacts, "formatPmosPhoneInput", "Account Contact phone formatting", failures)
    require(location_contacts, "formatPmosPhoneInput", "Service Location Contact phone formatting", failures)
    require(location_contacts, "Service Location Contacts JSON", "location-contact storage", failures)
    require(location_contacts, "getPmosServiceLocationContactIdentity_", "location-specific Google Contact identity", failures)
    require(location_contacts, "addresses: identity.address", "location-specific Google Contact address", failures)

    require(billing, "+ Add account holder billing address", "optional billing-address control", failures)
    ordered(billing, ["+ Add account holder billing address", "The primary account holder uses the primary service-location address"], "billing control/helper order", failures)
    require(billing, "Use primary service location instead", "billing-address reset", failures)
    require(billing, "suggestPmosAddresses", "billing address autocomplete", failures)
    require(billing, "confirmPmosSelectedAddress", "confirmed billing address", failures)
    require(account_model, "Account ID", "account/service-location grouping", failures)
    require(account_model, "Primary Service Location", "primary-location identity", failures)
    require(sheets_maintenance, "id=\"maintenanceStatus\"", "Sheets maintenance-create status selector", failures)
    require(shared_equipment, "status:maintenanceStatus?maintenanceStatus.value:'Active'", "Sheets maintenance-create status payload", failures)
    require(sheets_locations, "id=\"maintenanceStatus\"", "Sheets added-location status selector", failures)
    require(sheets_locations, "status:maintenance?el('maintenanceStatus').value:''", "Sheets added-location status payload", failures)
    require(maintenance_transaction, "statusMatch = /^(active|inactive|paused)$/i", "maintenance status allowlist", failures)
    require(maintenance_transaction, "'Status': request.status", "maintenance status persistence", failures)

    require(equipment, "Solar Heating Equipment", "compact Solar Heating Equipment UI", failures)
    require(equipment, "window.pmosEnsureCustomerBodyEnhancements=ensureBody", "shared Solar/body enhancement hook", failures)
    require(shared_equipment, "pmosConfigureSolarHeating", "core Solar Heating renderer hook", failures)
    require(equipment, "data-solar-add", "Solar Heater add-equipment dropdown", failures)
    ordered(equipment, ["pmos-solar-list\" data-solar-list", "pmos-solar-add\" data-solar-add"], "Solar equipment cards before add dropdown", failures)
    require(equipment, "Solar Automation", "Solar automation catalog option", failures)
    require(equipment, "PMOS_VALVE_ACTUATOR_CATALOG", "Solar actuator catalog", failures)
    require(equipment, "PMOS_EQUIPMENT_CATALOG.pump", "Solar pump catalog", failures)
    require(equipment, "data-body-equipment-notes", "body-specific Equipment Notes", failures)
    require(equipment_fixes, "clean.equipmentNotes", "Equipment Notes normalization", failures)
    require(equipment_fixes, "solarEquipment", "Solar normalization", failures)
    require(shared_equipment, "Nature2:[{name:'Fusion Soft 700", "Nature2 salt-system models", failures)
    require(shared_equipment, "Nature2:[{name:'Fusion In-Ground Mineral + Chlorine Tablet Feeder'", "Nature2 chlorine feeder", failures)
    require(shared_equipment, "data-equipment-field=\"partNumber\"", "separate equipment part-number field", failures)
    require(shared_equipment, "IntelliChem Chlorine Tank with Tank-Mounted Pump", "chemistry chlorine-tank default", failures)
    require(shared_equipment, "phProbe:{model:'IntelliChem pH Sensor',partNumber:'522186'}", "IntelliChem pH probe part number", failures)
    require(shared_equipment, "orpProbe:{model:'IntelliChem ORP Sensor',partNumber:'522187'}", "IntelliChem ORP probe part number", failures)
    require(shared_equipment, ".automation-fields>label", "matching automation-field typography", failures)
    require(shared_equipment, "chemistry-selectors", "compact chemistry Make/Model selectors", failures)
    require(shared_equipment, "chemistry-equipment-card", "single chemistry equipment detail card", failures)
    require(shared_equipment, "hydrateChemistryAutomationDetails", "chemistry equipment detail hydration", failures)
    require(equipment_enhancements, "PMOS_BODY_SHAPES", "body shape catalog", failures)
    require(equipment_enhancements, "data-body-field=\"volume\"", "body volume field", failures)
    require(equipment_enhancements, "standalone=bodyType==='spa'&&setup==='Self-Contained Unit'", "standalone hot-tub automation guard", failures)
    require(equipment_enhancements, "make.value='Floater'", "standalone hot-tub floater default", failures)
    ordered(equipment_enhancements, ["'Jandy'", "'Sta-Rite'", "'Nature2'"], "Nature2 make ordering", failures)
    forbid(shared_equipment, "prepareMainEquipmentPartNumbers", "blanket pump/filter/heater part-number fields", failures)
    forbid(shared_equipment, "automationPartNumber", "blanket Equipment Automation part-number field", failures)
    require(equipment, "grid.insertBefore(panel,coverTitle)", "Solar Heater grouped before Covers", failures)
    require(equipment, "pmosHydrateSolarEquipmentDetails", "Solar equipment edit hydration", failures)
    require(equipment, "handleSolarHeaterEvent", "Solar Heater delegated Web App activation", failures)
    require(equipment_enhancements, "pmosConfigureSharedBody", "shared Pool/Spa automation inheritance", failures)
    require(equipment_enhancements, "All equipment shared with Pool", "shared Pool/Spa equipment relationship summary", failures)
    require(shared_equipment, "VALVE_ACTUATOR:'Valve Actuator'", "spa-specific Valve Actuator equipment card", failures)
    forbid(equipment_enhancements, "pmosInstallSolarPanel", "duplicate Solar Heating panel", failures)
    forbid(equipment_enhancements, "data-solar-enabled", "duplicate Solar Heating checkbox list", failures)
    require(customer_editor, "pmosHydrateSolarEquipmentDetails(card,item.type,details)", "editor Solar equipment hydration", failures)
    forbid(equipment_enhancements, "type:'FLOW_CELL'", "duplicate standalone chemistry flow-cell item", failures)

    ordered(account_editor, ["const account = getPmosCustomerAccount_(customerId);", "const data = getPmosCustomerEditorData(customerId);"], "editor-token initialization order", failures)
    require(water, "maintenanceRemovalConfirmed !== true", "backend removal guard", failures)
    require(water, "removePmosWaterMaintenanceRouteRows_", "scoped maintenance-route removal", failures)
    require(water, "schedulePmosWaterMaintenanceRemovalCalendarSync_", "scoped maintenance Calendar cleanup", failures)
    require(notes_bridge, "scope.matches('#view-addcustomer,#view-addmaintenance,#ceBackdrop,#slBackdrop')", "no duplicate Web note injection", failures)
    require(notes_bridge, "if(window.__pmosCustomerFormEnhancementsLoaded)return", "no duplicate modern Sheets note injection", failures)
    require(notes_bridge, "if(window.__pmosProfileEnhancementLoaded||window.__pmosCustomerLifecycleProfile)return", "no duplicate modern profile note injection", failures)
    require(context_notes, "normalizePmosStoredContextNotes_", "stored note-envelope decoder", failures)
    require(context_notes, "PMOS_CONTEXT_NOTES_V1:", "legacy categorized-note envelope support", failures)
    require(maintenance_contacts, "data-pmos-native-maint-contacts", "no duplicate maintenance contact injection", failures)
    require(maintenance_contacts, "savePmosAccountBillingAddress_", "maintenance billing persistence", failures)
    require(account_editor, "listName: primary.listName || usefulAccountListName", "customer name preferred over Customer ID fallback", failures)
    require(lifecycle, "_pmosLifecycleComplete", "lifecycle payload completion marker", failures)
    require(lifecycle, "pmosAttachCustomerLifecycleEditorData_", "single lifecycle editor enrichment helper", failures)
    require(lifecycle_runtime, "pmosAttachCustomerLifecycleEditorData_(baseEditorRuntime(customerId), customerId)", "shared Sheets/Web lifecycle enrichment", failures)
    require(sheets_editor_lifecycle, "pmos-sheets-editor-loading", "Sheets editor loading gate", failures)
    require(sheets_editor_lifecycle, "requestAnimationFrame(function(){requestAnimationFrame(revealEditor)})", "Sheets editor reveal after complete contact hydration", failures)
    require(sheets_editor_lifecycle, "validateEditor()", "Sheets editor exact-field validation", failures)
    require(sheets_editor_lifecycle, "firstField.parentNode.insertBefore(lastField,firstField)", "Sheets editor Last Name-first ordering", failures)
    require(editor, "await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))", "Web editor reveal after complete hydration", failures)
    require(editor, "markInvalid(input,message)", "Web editor exact-field validation", failures)
    require(lifecycle, "<h3>Contacts</h3>", "combined deduplicated profile contacts", failures)
    require(lifecycle, "request.calendarTitle = locationName", "one-way Service Location to Calendar title synchronization", failures)
    require(sheets_editor_lifecycle, "watchTimer=setInterval(refresh,100)", "Sheets editor late-payload hydration", failures)
    forbid(sheets_editor_lifecycle, "},5000)", "five-second Sheets editor hydration cutoff", failures)
    require(editor, "loadCustomerData(id)", "bounded Web editor load", failures)
    forbid(legacy_contact_bridge, "const baseLifecycleEditor = getPmosCustomerLifecycleEditorData", "duplicate legacy lifecycle editor enrichment", failures)

    if failures:
        print("PMOS customer lifecycle contract failed:")
        for failure in failures:
            print(" -", failure)
        raise SystemExit(1)
    print("PMOS customer lifecycle contract clean: customer, account, service-location, notes, equipment, and maintenance safeguards present.")


if __name__ == "__main__":
    main()
